version: '3.8'

services:
  php:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://symfony:!ChangeMe!@database:5432/pbd2h24asc_stundenplan_db?serverVersion=16&charset=utf8"

  worker:
    build: .
    command: php bin/console messenger:consume scheduler_main --repeat
    volumes:
      - .:/var/www/html
    depends_on:
      database:
        condition: service_healthy
    restart: always
    environment:
      DATABASE_URL: "postgresql://symfony:!ChangeMe!@database:5432/pbd2h24asc_stundenplan_db?serverVersion=16&charset=utf8"

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: pbd2h24asc_stundenplan_db
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: '!ChangeMe!'
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data:rw
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=$$POSTGRES_PASSWORD pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
