<?php

namespace ContainerM1Tjp7g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JBf5zxbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jBf5zxb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jBf5zxb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'serializer' => ['privates', 'App\\OpenApi\\Service\\JmsSerializer', 'getJmsSerializerService', true],
        ], [
            'serializer' => '?',
        ]);
    }
}
