<?php

namespace ContainerM1Tjp7g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2F9d3HUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2F9d3HU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2F9d3HU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'exception' => ['privates', '.errored..service_locator.2F9d3HU.Symfony\\Component\\HttpKernel\\Exception\\HttpException', NULL, 'Cannot autowire service ".service_locator.2F9d3HU": it references class "Symfony\\Component\\HttpKernel\\Exception\\HttpException" but no such service exists.'],
        ], [
            'exception' => 'Symfony\\Component\\HttpKernel\\Exception\\HttpException',
        ]);
    }
}
