<?php

namespace ContainerM1Tjp7g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UQQzquJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UQQzquJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UQQzquJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'server' => ['privates', 'App\\OpenApi\\Api\\ApiServer', 'getApiServerService', true],
        ], [
            'server' => 'App\\OpenApi\\Api\\ApiServer',
        ]);
    }
}
