<?php

namespace ContainerM1Tjp7g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'http-kernel'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'http-kernel'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ArgumentResolver'.\DIRECTORY_SEPARATOR.'ServiceValueResolver.php';

        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'open_api_server.controller.calendar::createErrorResponse' => ['privates', '.service_locator.2F9d3HU.open_api_server.controller.calendar::createErrorResponse()', 'get_ServiceLocator_2F9d3HU_OpenApiServer_Controller_CalendarcreateErrorResponseService', true],
            'open_api_server.controller.class::createErrorResponse' => ['privates', '.service_locator.2F9d3HU.open_api_server.controller.class::createErrorResponse()', 'get_ServiceLocator_2F9d3HU_OpenApiServer_Controller_ClasscreateErrorResponseService', true],
            'open_api_server.controller.password::createErrorResponse' => ['privates', '.service_locator.2F9d3HU.open_api_server.controller.password::createErrorResponse()', 'get_ServiceLocator_2F9d3HU_OpenApiServer_Controller_PasswordcreateErrorResponseService', true],
            'open_api_server.controller.user::createErrorResponse' => ['privates', '.service_locator.2F9d3HU.open_api_server.controller.user::createErrorResponse()', 'get_ServiceLocator_2F9d3HU_OpenApiServer_Controller_UsercreateErrorResponseService', true],
            'App\\OpenApi\\Controller\\CalendarController::setValidator' => ['privates', '.service_locator.6KUoiWU.App\\OpenApi\\Controller\\CalendarController::setValidator()', 'getCalendarControllersetValidatorService', true],
            'App\\OpenApi\\Controller\\CalendarController::setSerializer' => ['privates', '.service_locator.jBf5zxb.App\\OpenApi\\Controller\\CalendarController::setSerializer()', 'getCalendarControllersetSerializerService', true],
            'App\\OpenApi\\Controller\\CalendarController::setApiServer' => ['privates', '.service_locator.UQQzquJ.App\\OpenApi\\Controller\\CalendarController::setApiServer()', 'getCalendarControllersetApiServerService', true],
            'App\\OpenApi\\Controller\\CalendarController::createErrorResponse' => ['privates', '.service_locator.2F9d3HU.App\\OpenApi\\Controller\\CalendarController::createErrorResponse()', 'getCalendarControllercreateErrorResponseService', true],
            'App\\OpenApi\\Controller\\ClassController::setValidator' => ['privates', '.service_locator.6KUoiWU.App\\OpenApi\\Controller\\ClassController::setValidator()', 'getClassControllersetValidatorService', true],
            'App\\OpenApi\\Controller\\ClassController::setSerializer' => ['privates', '.service_locator.jBf5zxb.App\\OpenApi\\Controller\\ClassController::setSerializer()', 'getClassControllersetSerializerService', true],
            'App\\OpenApi\\Controller\\ClassController::setApiServer' => ['privates', '.service_locator.UQQzquJ.App\\OpenApi\\Controller\\ClassController::setApiServer()', 'getClassControllersetApiServerService', true],
            'App\\OpenApi\\Controller\\ClassController::createErrorResponse' => ['privates', '.service_locator.2F9d3HU.App\\OpenApi\\Controller\\ClassController::createErrorResponse()', 'getClassControllercreateErrorResponseService', true],
            'App\\OpenApi\\Controller\\Controller::setValidator' => ['privates', '.service_locator.6KUoiWU.App\\OpenApi\\Controller\\Controller::setValidator()', 'getControllersetValidatorService', true],
            'App\\OpenApi\\Controller\\Controller::setSerializer' => ['privates', '.service_locator.jBf5zxb.App\\OpenApi\\Controller\\Controller::setSerializer()', 'getControllersetSerializerService', true],
            'App\\OpenApi\\Controller\\Controller::setApiServer' => ['privates', '.service_locator.UQQzquJ.App\\OpenApi\\Controller\\Controller::setApiServer()', 'getControllersetApiServerService', true],
            'App\\OpenApi\\Controller\\Controller::createErrorResponse' => ['privates', '.service_locator.2F9d3HU.App\\OpenApi\\Controller\\Controller::createErrorResponse()', 'getControllercreateErrorResponseService', true],
            'App\\OpenApi\\Controller\\PasswordController::setValidator' => ['privates', '.service_locator.6KUoiWU.App\\OpenApi\\Controller\\PasswordController::setValidator()', 'getPasswordControllersetValidatorService', true],
            'App\\OpenApi\\Controller\\PasswordController::setSerializer' => ['privates', '.service_locator.jBf5zxb.App\\OpenApi\\Controller\\PasswordController::setSerializer()', 'getPasswordControllersetSerializerService', true],
            'App\\OpenApi\\Controller\\PasswordController::setApiServer' => ['privates', '.service_locator.UQQzquJ.App\\OpenApi\\Controller\\PasswordController::setApiServer()', 'getPasswordControllersetApiServerService', true],
            'App\\OpenApi\\Controller\\PasswordController::createErrorResponse' => ['privates', '.service_locator.2F9d3HU.App\\OpenApi\\Controller\\PasswordController::createErrorResponse()', 'getPasswordControllercreateErrorResponseService', true],
            'App\\OpenApi\\Controller\\UserController::setValidator' => ['privates', '.service_locator.6KUoiWU.App\\OpenApi\\Controller\\UserController::setValidator()', 'getUserControllersetValidatorService', true],
            'App\\OpenApi\\Controller\\UserController::setSerializer' => ['privates', '.service_locator.jBf5zxb.App\\OpenApi\\Controller\\UserController::setSerializer()', 'getUserControllersetSerializerService', true],
            'App\\OpenApi\\Controller\\UserController::setApiServer' => ['privates', '.service_locator.UQQzquJ.App\\OpenApi\\Controller\\UserController::setApiServer()', 'getUserControllersetApiServerService', true],
            'App\\OpenApi\\Controller\\UserController::createErrorResponse' => ['privates', '.service_locator.2F9d3HU.App\\OpenApi\\Controller\\UserController::createErrorResponse()', 'getUserControllercreateErrorResponseService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'open_api_server.controller.calendar:createErrorResponse' => ['privates', '.service_locator.2F9d3HU.open_api_server.controller.calendar::createErrorResponse()', 'get_ServiceLocator_2F9d3HU_OpenApiServer_Controller_CalendarcreateErrorResponseService', true],
            'open_api_server.controller.class:createErrorResponse' => ['privates', '.service_locator.2F9d3HU.open_api_server.controller.class::createErrorResponse()', 'get_ServiceLocator_2F9d3HU_OpenApiServer_Controller_ClasscreateErrorResponseService', true],
            'open_api_server.controller.password:createErrorResponse' => ['privates', '.service_locator.2F9d3HU.open_api_server.controller.password::createErrorResponse()', 'get_ServiceLocator_2F9d3HU_OpenApiServer_Controller_PasswordcreateErrorResponseService', true],
            'open_api_server.controller.user:createErrorResponse' => ['privates', '.service_locator.2F9d3HU.open_api_server.controller.user::createErrorResponse()', 'get_ServiceLocator_2F9d3HU_OpenApiServer_Controller_UsercreateErrorResponseService', true],
            'App\\OpenApi\\Controller\\CalendarController:setValidator' => ['privates', '.service_locator.6KUoiWU.App\\OpenApi\\Controller\\CalendarController::setValidator()', 'getCalendarControllersetValidatorService', true],
            'App\\OpenApi\\Controller\\CalendarController:setSerializer' => ['privates', '.service_locator.jBf5zxb.App\\OpenApi\\Controller\\CalendarController::setSerializer()', 'getCalendarControllersetSerializerService', true],
            'App\\OpenApi\\Controller\\CalendarController:setApiServer' => ['privates', '.service_locator.UQQzquJ.App\\OpenApi\\Controller\\CalendarController::setApiServer()', 'getCalendarControllersetApiServerService', true],
            'App\\OpenApi\\Controller\\CalendarController:createErrorResponse' => ['privates', '.service_locator.2F9d3HU.App\\OpenApi\\Controller\\CalendarController::createErrorResponse()', 'getCalendarControllercreateErrorResponseService', true],
            'App\\OpenApi\\Controller\\ClassController:setValidator' => ['privates', '.service_locator.6KUoiWU.App\\OpenApi\\Controller\\ClassController::setValidator()', 'getClassControllersetValidatorService', true],
            'App\\OpenApi\\Controller\\ClassController:setSerializer' => ['privates', '.service_locator.jBf5zxb.App\\OpenApi\\Controller\\ClassController::setSerializer()', 'getClassControllersetSerializerService', true],
            'App\\OpenApi\\Controller\\ClassController:setApiServer' => ['privates', '.service_locator.UQQzquJ.App\\OpenApi\\Controller\\ClassController::setApiServer()', 'getClassControllersetApiServerService', true],
            'App\\OpenApi\\Controller\\ClassController:createErrorResponse' => ['privates', '.service_locator.2F9d3HU.App\\OpenApi\\Controller\\ClassController::createErrorResponse()', 'getClassControllercreateErrorResponseService', true],
            'App\\OpenApi\\Controller\\Controller:setValidator' => ['privates', '.service_locator.6KUoiWU.App\\OpenApi\\Controller\\Controller::setValidator()', 'getControllersetValidatorService', true],
            'App\\OpenApi\\Controller\\Controller:setSerializer' => ['privates', '.service_locator.jBf5zxb.App\\OpenApi\\Controller\\Controller::setSerializer()', 'getControllersetSerializerService', true],
            'App\\OpenApi\\Controller\\Controller:setApiServer' => ['privates', '.service_locator.UQQzquJ.App\\OpenApi\\Controller\\Controller::setApiServer()', 'getControllersetApiServerService', true],
            'App\\OpenApi\\Controller\\Controller:createErrorResponse' => ['privates', '.service_locator.2F9d3HU.App\\OpenApi\\Controller\\Controller::createErrorResponse()', 'getControllercreateErrorResponseService', true],
            'App\\OpenApi\\Controller\\PasswordController:setValidator' => ['privates', '.service_locator.6KUoiWU.App\\OpenApi\\Controller\\PasswordController::setValidator()', 'getPasswordControllersetValidatorService', true],
            'App\\OpenApi\\Controller\\PasswordController:setSerializer' => ['privates', '.service_locator.jBf5zxb.App\\OpenApi\\Controller\\PasswordController::setSerializer()', 'getPasswordControllersetSerializerService', true],
            'App\\OpenApi\\Controller\\PasswordController:setApiServer' => ['privates', '.service_locator.UQQzquJ.App\\OpenApi\\Controller\\PasswordController::setApiServer()', 'getPasswordControllersetApiServerService', true],
            'App\\OpenApi\\Controller\\PasswordController:createErrorResponse' => ['privates', '.service_locator.2F9d3HU.App\\OpenApi\\Controller\\PasswordController::createErrorResponse()', 'getPasswordControllercreateErrorResponseService', true],
            'App\\OpenApi\\Controller\\UserController:setValidator' => ['privates', '.service_locator.6KUoiWU.App\\OpenApi\\Controller\\UserController::setValidator()', 'getUserControllersetValidatorService', true],
            'App\\OpenApi\\Controller\\UserController:setSerializer' => ['privates', '.service_locator.jBf5zxb.App\\OpenApi\\Controller\\UserController::setSerializer()', 'getUserControllersetSerializerService', true],
            'App\\OpenApi\\Controller\\UserController:setApiServer' => ['privates', '.service_locator.UQQzquJ.App\\OpenApi\\Controller\\UserController::setApiServer()', 'getUserControllersetApiServerService', true],
            'App\\OpenApi\\Controller\\UserController:createErrorResponse' => ['privates', '.service_locator.2F9d3HU.App\\OpenApi\\Controller\\UserController::createErrorResponse()', 'getUserControllercreateErrorResponseService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'open_api_server.controller.calendar::createErrorResponse' => '?',
            'open_api_server.controller.class::createErrorResponse' => '?',
            'open_api_server.controller.password::createErrorResponse' => '?',
            'open_api_server.controller.user::createErrorResponse' => '?',
            'App\\OpenApi\\Controller\\CalendarController::setValidator' => '?',
            'App\\OpenApi\\Controller\\CalendarController::setSerializer' => '?',
            'App\\OpenApi\\Controller\\CalendarController::setApiServer' => '?',
            'App\\OpenApi\\Controller\\CalendarController::createErrorResponse' => '?',
            'App\\OpenApi\\Controller\\ClassController::setValidator' => '?',
            'App\\OpenApi\\Controller\\ClassController::setSerializer' => '?',
            'App\\OpenApi\\Controller\\ClassController::setApiServer' => '?',
            'App\\OpenApi\\Controller\\ClassController::createErrorResponse' => '?',
            'App\\OpenApi\\Controller\\Controller::setValidator' => '?',
            'App\\OpenApi\\Controller\\Controller::setSerializer' => '?',
            'App\\OpenApi\\Controller\\Controller::setApiServer' => '?',
            'App\\OpenApi\\Controller\\Controller::createErrorResponse' => '?',
            'App\\OpenApi\\Controller\\PasswordController::setValidator' => '?',
            'App\\OpenApi\\Controller\\PasswordController::setSerializer' => '?',
            'App\\OpenApi\\Controller\\PasswordController::setApiServer' => '?',
            'App\\OpenApi\\Controller\\PasswordController::createErrorResponse' => '?',
            'App\\OpenApi\\Controller\\UserController::setValidator' => '?',
            'App\\OpenApi\\Controller\\UserController::setSerializer' => '?',
            'App\\OpenApi\\Controller\\UserController::setApiServer' => '?',
            'App\\OpenApi\\Controller\\UserController::createErrorResponse' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'open_api_server.controller.calendar:createErrorResponse' => '?',
            'open_api_server.controller.class:createErrorResponse' => '?',
            'open_api_server.controller.password:createErrorResponse' => '?',
            'open_api_server.controller.user:createErrorResponse' => '?',
            'App\\OpenApi\\Controller\\CalendarController:setValidator' => '?',
            'App\\OpenApi\\Controller\\CalendarController:setSerializer' => '?',
            'App\\OpenApi\\Controller\\CalendarController:setApiServer' => '?',
            'App\\OpenApi\\Controller\\CalendarController:createErrorResponse' => '?',
            'App\\OpenApi\\Controller\\ClassController:setValidator' => '?',
            'App\\OpenApi\\Controller\\ClassController:setSerializer' => '?',
            'App\\OpenApi\\Controller\\ClassController:setApiServer' => '?',
            'App\\OpenApi\\Controller\\ClassController:createErrorResponse' => '?',
            'App\\OpenApi\\Controller\\Controller:setValidator' => '?',
            'App\\OpenApi\\Controller\\Controller:setSerializer' => '?',
            'App\\OpenApi\\Controller\\Controller:setApiServer' => '?',
            'App\\OpenApi\\Controller\\Controller:createErrorResponse' => '?',
            'App\\OpenApi\\Controller\\PasswordController:setValidator' => '?',
            'App\\OpenApi\\Controller\\PasswordController:setSerializer' => '?',
            'App\\OpenApi\\Controller\\PasswordController:setApiServer' => '?',
            'App\\OpenApi\\Controller\\PasswordController:createErrorResponse' => '?',
            'App\\OpenApi\\Controller\\UserController:setValidator' => '?',
            'App\\OpenApi\\Controller\\UserController:setSerializer' => '?',
            'App\\OpenApi\\Controller\\UserController:setApiServer' => '?',
            'App\\OpenApi\\Controller\\UserController:createErrorResponse' => '?',
        ]));
    }
}
