<?php

namespace ContainerM1Tjp7g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiServerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\OpenApi\Api\ApiServer' shared autowired service.
     *
     * @return \App\OpenApi\Api\ApiServer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'OpenApi'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'ApiServer.php';

        return $container->privates['App\\OpenApi\\Api\\ApiServer'] = new \App\OpenApi\Api\ApiServer();
    }
}
