<?php

namespace ContainerM1Tjp7g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClassEntityListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Infrastructure\EventListener\ClassEntityListener' shared autowired service.
     *
     * @return \App\Infrastructure\EventListener\ClassEntityListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Infrastructure'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'ClassEntityListener.php';

        return $container->privates['App\\Infrastructure\\EventListener\\ClassEntityListener'] = new \App\Infrastructure\EventListener\ClassEntityListener();
    }
}
