<?php

namespace ContainerM1Tjp7g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClassController2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Presentation\Http\Controller\ClassController' shared autowired service.
     *
     * @return \App\Presentation\Http\Controller\ClassController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Presentation'.\DIRECTORY_SEPARATOR.'Http'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ClassController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Application'.\DIRECTORY_SEPARATOR.'Class'.\DIRECTORY_SEPARATOR.'ClassApplicationService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Application'.\DIRECTORY_SEPARATOR.'Shared'.\DIRECTORY_SEPARATOR.'UserContext.php';

        $container->services['App\\Presentation\\Http\\Controller\\ClassController'] = $instance = new \App\Presentation\Http\Controller\ClassController(new \App\Application\Class\ClassApplicationService(($container->privates['App\\Domain\\Class\\Service\\ClassService'] ?? $container->load('getClassServiceService')), ($container->privates['App\\Application\\Shared\\UserContext'] ??= new \App\Application\Shared\UserContext())));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Presentation\\Http\\Controller\\ClassController', $container));

        return $instance;
    }
}
