<?php

namespace ContainerM1Tjp7g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClassServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Domain\Class\Service\ClassService' shared autowired service.
     *
     * @return \App\Domain\Class\Service\ClassService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Domain'.\DIRECTORY_SEPARATOR.'Class'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ClassService.php';

        return $container->privates['App\\Domain\\Class\\Service\\ClassService'] = new \App\Domain\Class\Service\ClassService(($container->privates['App\\Infrastructure\\Repository\\ClassRepository'] ?? $container->load('getClassRepositoryService')), ($container->privates['App\\Infrastructure\\Repository\\PersonalDataRepository'] ?? $container->load('getPersonalDataRepositoryService')));
    }
}
