<?php

namespace ContainerM1Tjp7g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCalendarController2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Presentation\Http\Controller\CalendarController' shared autowired service.
     *
     * @return \App\Presentation\Http\Controller\CalendarController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Presentation'.\DIRECTORY_SEPARATOR.'Http'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'CalendarController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Application'.\DIRECTORY_SEPARATOR.'Calendar'.\DIRECTORY_SEPARATOR.'CalendarApplicationService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Domain'.\DIRECTORY_SEPARATOR.'Calendar'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'CalendarService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Domain'.\DIRECTORY_SEPARATOR.'Calendar'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'NotedChangeRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Infrastructure'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'NotedChangeRepository.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Application'.\DIRECTORY_SEPARATOR.'Shared'.\DIRECTORY_SEPARATOR.'UserContext.php';

        $container->services['App\\Presentation\\Http\\Controller\\CalendarController'] = $instance = new \App\Presentation\Http\Controller\CalendarController(new \App\Application\Calendar\CalendarApplicationService(new \App\Domain\Calendar\Service\CalendarService(new \App\Infrastructure\Repository\NotedChangeRepository(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'))), ($container->services['doctrine.dbal.default_connection'] ?? $container->load('getDoctrine_Dbal_DefaultConnectionService'))), ($container->privates['App\\Application\\Shared\\UserContext'] ??= new \App\Application\Shared\UserContext())));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Presentation\\Http\\Controller\\CalendarController', $container));

        return $instance;
    }
}
