<?php

namespace ContainerM1Tjp7g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOpenApiServer_Service_ValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'open_api_server.service.validator' shared service.
     *
     * @return \App\OpenApi\Service\SymfonyValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'OpenApi'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ValidatorInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'OpenApi'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'SymfonyValidator.php';

        return $container->privates['open_api_server.service.validator'] = new \App\OpenApi\Service\SymfonyValidator(($container->privates['validator'] ?? $container->load('getValidatorService')));
    }
}
