<?php

namespace ContainerM1Tjp7g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPasswordControllersetValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6KUoiWU.App\OpenApi\Controller\PasswordController::setValidator()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6KUoiWU.App\\OpenApi\\Controller\\PasswordController::setValidator()'] = ($container->privates['.service_locator.6KUoiWU'] ?? $container->load('get_ServiceLocator_6KUoiWUService'))->withContext('App\\OpenApi\\Controller\\PasswordController::setValidator()', $container);
    }
}
