<?php

namespace ContainerM1Tjp7g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPasswordControllersetApiServerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UQQzquJ.App\OpenApi\Controller\PasswordController::setApiServer()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UQQzquJ.App\\OpenApi\\Controller\\PasswordController::setApiServer()'] = ($container->privates['.service_locator.UQQzquJ'] ?? $container->load('get_ServiceLocator_UQQzquJService'))->withContext('App\\OpenApi\\Controller\\PasswordController::setApiServer()', $container);
    }
}
