<?php

namespace ContainerM1Tjp7g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPasswordControllercreateErrorResponseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2F9d3HU.App\OpenApi\Controller\PasswordController::createErrorResponse()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2F9d3HU.App\\OpenApi\\Controller\\PasswordController::createErrorResponse()'] = ($container->privates['.service_locator.2F9d3HU'] ?? $container->load('get_ServiceLocator_2F9d3HUService'))->withContext('App\\OpenApi\\Controller\\PasswordController::createErrorResponse()', $container);
    }
}
