<?php

namespace ContainerM1Tjp7g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllersetSerializerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jBf5zxb.App\OpenApi\Controller\UserController::setSerializer()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jBf5zxb.App\\OpenApi\\Controller\\UserController::setSerializer()'] = ($container->privates['.service_locator.jBf5zxb'] ?? $container->load('get_ServiceLocator_JBf5zxbService'))->withContext('App\\OpenApi\\Controller\\UserController::setSerializer()', $container);
    }
}
