<?php

namespace ContainerM1Tjp7g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserController2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Presentation\Http\Controller\UserController' shared autowired service.
     *
     * @return \App\Presentation\Http\Controller\UserController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Presentation'.\DIRECTORY_SEPARATOR.'Http'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'UserController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Application'.\DIRECTORY_SEPARATOR.'User'.\DIRECTORY_SEPARATOR.'UserApplicationService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Domain'.\DIRECTORY_SEPARATOR.'User'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'UserService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Domain'.\DIRECTORY_SEPARATOR.'User'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'UserRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Infrastructure'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'UserRepository.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Application'.\DIRECTORY_SEPARATOR.'User'.\DIRECTORY_SEPARATOR.'PasswordApplicationService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Domain'.\DIRECTORY_SEPARATOR.'Password'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'PasswordResetService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'mailer'.\DIRECTORY_SEPARATOR.'MailerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'mailer'.\DIRECTORY_SEPARATOR.'Mailer.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Application'.\DIRECTORY_SEPARATOR.'Shared'.\DIRECTORY_SEPARATOR.'UserContext.php';

        $a = new \App\Infrastructure\Repository\UserRepository(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $container->services['App\\Presentation\\Http\\Controller\\UserController'] = $instance = new \App\Presentation\Http\Controller\UserController(new \App\Application\User\UserApplicationService(new \App\Domain\User\Service\UserService($a, ($container->privates['App\\Infrastructure\\Repository\\PersonalDataRepository'] ?? $container->load('getPersonalDataRepositoryService')), ($container->privates['App\\Infrastructure\\Repository\\ClassRepository'] ?? $container->load('getClassRepositoryService'))), ($container->privates['App\\Domain\\Class\\Service\\ClassService'] ?? $container->load('getClassServiceService')), ($container->privates['App\\Application\\Shared\\UserContext'] ??= new \App\Application\Shared\UserContext())), new \App\Application\User\PasswordApplicationService(new \App\Domain\Password\Service\PasswordResetService($a, new \Symfony\Component\Mailer\Mailer(($container->privates['mailer.transports'] ?? $container->load('getMailer_TransportsService')), NULL, ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container))))));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Presentation\\Http\\Controller\\UserController', $container));

        return $instance;
    }
}
