<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM1Tjp7g\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM1Tjp7g/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM1Tjp7g.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM1Tjp7g\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerM1Tjp7g\App_KernelDevDebugContainer([
    'container.build_hash' => 'M1Tjp7g',
    'container.build_id' => 'dc9d1aa7',
    'container.build_time' => 1779392073,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM1Tjp7g');
