<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'open_api_server_calendar_restapiphpactiongetcalendarget' => [[], ['_controller' => 'open_api_server.controller.calendar::restapiPhpactiongetCalendarGetAction'], [], [['text', '/restapi.php?action=getCalendar']], [], [], []],
    'open_api_server_calendar_restapiphpactiongetchangesget' => [[], ['_controller' => 'open_api_server.controller.calendar::restapiPhpactiongetChangesGetAction'], [], [['text', '/restapi.php?action=getChanges']], [], [], []],
    'open_api_server_calendar_restapiphpactiongetnotedchangesget' => [[], ['_controller' => 'open_api_server.controller.calendar::restapiPhpactiongetNotedChangesGetAction'], [], [['text', '/restapi.php?action=getNotedChanges']], [], [], []],
    'open_api_server_calendar_restapiphpactionwritenotedchangespost' => [[], ['_controller' => 'open_api_server.controller.calendar::restapiPhpactionwriteNotedChangesPostAction'], [], [['text', '/restapi.php?action=writeNotedChanges']], [], [], []],
    'open_api_server_class_restapiphpactiondeleteclassididdelete' => [['id'], ['_controller' => 'open_api_server.controller.class::restapiPhpactiondeleteClassididDeleteAction'], ['id' => '[a-z0-9]+'], [['variable', '=', '[a-z0-9]+', 'id', true], ['text', '/restapi.php?action=deleteClass&id']], [], [], []],
    'open_api_server_class_restapiphpactiongetclassbyidget' => [[], ['_controller' => 'open_api_server.controller.class::restapiPhpactiongetClassByIdGetAction'], [], [['text', '/restapi.php?action=getClassById']], [], [], []],
    'open_api_server_class_restapiphpactiongetclassget' => [[], ['_controller' => 'open_api_server.controller.class::restapiPhpactiongetClassGetAction'], [], [['text', '/restapi.php?action=getClass']], [], [], []],
    'open_api_server_class_restapiphpactionupdateclassididput' => [['id'], ['_controller' => 'open_api_server.controller.class::restapiPhpactionupdateClassididPutAction'], ['id' => '[a-z0-9]+'], [['variable', '=', '[a-z0-9]+', 'id', true], ['text', '/restapi.php?action=updateClass&id']], [], [], []],
    'open_api_server_class_restapiphpactionwriteclasspost' => [[], ['_controller' => 'open_api_server.controller.class::restapiPhpactionwriteClassPostAction'], [], [['text', '/restapi.php?action=writeClass']], [], [], []],
    'open_api_server_password_restapiphpactionrequestpasswordresetpost' => [[], ['_controller' => 'open_api_server.controller.password::restapiPhpactionrequestPasswordResetPostAction'], [], [['text', '/restapi.php?action=requestPasswordReset']], [], [], []],
    'open_api_server_password_restapiphpactionresetpasswordpost' => [[], ['_controller' => 'open_api_server.controller.password::restapiPhpactionresetPasswordPostAction'], [], [['text', '/restapi.php?action=resetPassword']], [], [], []],
    'open_api_server_user_apiusersregisterpost' => [[], ['_controller' => 'open_api_server.controller.user::apiUsersRegisterPostAction'], [], [['text', '/api/users/register']], [], [], []],
    'open_api_server_user_restapiphpactiongetuserget' => [[], ['_controller' => 'open_api_server.controller.user::restapiPhpactiongetUserGetAction'], [], [['text', '/restapi.php?action=getUser']], [], [], []],
    'open_api_server_user_restapiphpactionprofileget' => [[], ['_controller' => 'open_api_server.controller.user::restapiPhpactionprofileGetAction'], [], [['text', '/restapi.php?action=profile']], [], [], []],
    'open_api_server_user_restapiphpactionupdateprofileput' => [[], ['_controller' => 'open_api_server.controller.user::restapiPhpactionupdateProfilePutAction'], [], [['text', '/restapi.php?action=updateProfile']], [], [], []],
    'open_api_server_user_restapiphpactionwriteuserpost' => [[], ['_controller' => 'open_api_server.controller.user::restapiPhpactionwriteUserPostAction'], [], [['text', '/restapi.php?action=writeUser']], [], [], []],
];
