<?php

/**
 * CalendarController
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi\Controller
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App API
 *
 * REST API für die Klassenverwaltung und Stundenplan-Verwaltung
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\OpenApi\Controller;

use \Exception;
use JMS\Serializer\Exception\RuntimeException as SerializerRuntimeException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Symfony\Component\Validator\Constraints as Assert;
use App\OpenApi\Api\CalendarApiInterface;
use App\OpenApi\Model\CalendarEvent;
use App\OpenApi\Model\ChangeRecord;
use App\OpenApi\Model\Error;
use App\OpenApi\Model\NotedChange;
use App\OpenApi\Model\RestapiPhpActionWriteNotedChangesPost200Response;
use App\OpenApi\Model\RestapiPhpActionWriteNotedChangesPostRequest;

/**
 * CalendarController Class Doc Comment
 *
 * @category Class
 * @package  App\OpenApi\Controller
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
class CalendarController extends Controller
{

    /**
     * Operation restapiPhpactiongetCalendarGet
     *
     * Aktuellen Stundenplan abrufen
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function restapiPhpactiongetCalendarGetAction(Request $request)
    {
        // Figure out what data format to return to the client
        $produces = ['application/json'];
        // Figure out what the client accepts
        $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
        $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
        if ($responseFormat === null) {
            return new Response('', 406);
        }

        // Handle authentication

        // Read out all input parameter values into variables

        // Use the default value if no value was provided

        // Validate the input values


        try {
            $handler = $this->getApiHandler();


            // Make the call to the business logic
            $responseCode = 200;
            $responseHeaders = [];

            $result = $handler->restapiPhpactiongetCalendarGet($responseCode, $responseHeaders);

            $message = match($responseCode) {
                200 => 'Stundenplan erfolgreich abgerufen',
                500 => 'Stundenplan konnte nicht geladen werden',
                default => '',
            };

            return new Response(
                $result !== null ?$this->serialize($result, $responseFormat):'',
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-OpenAPI-Message' => $message
                    ]
                )
            );
        } catch (\Throwable $fallthrough) {
            return $this->createErrorResponse(new HttpException(500, 'An unsuspected error occurred.', $fallthrough));
        }
    }

    /**
     * Operation restapiPhpactiongetChangesGet
     *
     * Terminänderungen abrufen
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function restapiPhpactiongetChangesGetAction(Request $request)
    {
        // Figure out what data format to return to the client
        $produces = ['application/json'];
        // Figure out what the client accepts
        $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
        $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
        if ($responseFormat === null) {
            return new Response('', 406);
        }

        // Handle authentication

        // Read out all input parameter values into variables

        // Use the default value if no value was provided

        // Validate the input values


        try {
            $handler = $this->getApiHandler();


            // Make the call to the business logic
            $responseCode = 200;
            $responseHeaders = [];

            $result = $handler->restapiPhpactiongetChangesGet($responseCode, $responseHeaders);

            $message = match($responseCode) {
                200 => 'Änderungen erfolgreich abgerufen',
                500 => 'Änderungen konnten nicht abgefragt werden',
                default => '',
            };

            return new Response(
                $result !== null ?$this->serialize($result, $responseFormat):'',
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-OpenAPI-Message' => $message
                    ]
                )
            );
        } catch (\Throwable $fallthrough) {
            return $this->createErrorResponse(new HttpException(500, 'An unsuspected error occurred.', $fallthrough));
        }
    }

    /**
     * Operation restapiPhpactiongetNotedChangesGet
     *
     * Gelesene Änderungen abrufen
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function restapiPhpactiongetNotedChangesGetAction(Request $request)
    {
        // Figure out what data format to return to the client
        $produces = ['application/json'];
        // Figure out what the client accepts
        $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
        $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
        if ($responseFormat === null) {
            return new Response('', 406);
        }

        // Handle authentication

        // Read out all input parameter values into variables

        // Use the default value if no value was provided

        // Validate the input values


        try {
            $handler = $this->getApiHandler();


            // Make the call to the business logic
            $responseCode = 200;
            $responseHeaders = [];

            $result = $handler->restapiPhpactiongetNotedChangesGet($responseCode, $responseHeaders);

            $message = match($responseCode) {
                200 => 'Gelesene Änderungen erfolgreich abgerufen',
                500 => 'Fehler beim Abrufen der gelesenen Termine',
                default => '',
            };

            return new Response(
                $result !== null ?$this->serialize($result, $responseFormat):'',
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-OpenAPI-Message' => $message
                    ]
                )
            );
        } catch (\Throwable $fallthrough) {
            return $this->createErrorResponse(new HttpException(500, 'An unsuspected error occurred.', $fallthrough));
        }
    }

    /**
     * Operation restapiPhpactionwriteNotedChangesPost
     *
     * Terminänderung als gelesen markieren
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function restapiPhpactionwriteNotedChangesPostAction(Request $request)
    {
        // Make sure that the client is providing something that we can consume
        $consumes = ['application/json'];
        if (!static::isContentTypeAllowed($request, $consumes)) {
            // We can't consume the content that the client is sending us
            return new Response('', 415);
        }

        // Figure out what data format to return to the client
        $produces = ['application/json'];
        // Figure out what the client accepts
        $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
        $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
        if ($responseFormat === null) {
            return new Response('', 406);
        }

        // Handle authentication

        // Read out all input parameter values into variables
        $restapiPhpActionWriteNotedChangesPostRequest = $request->getContent();

        // Use the default value if no value was provided

        // Deserialize the input values that needs it
        try {
            $inputFormat = $request->getMimeType($request->getContentTypeFormat());
            $restapiPhpActionWriteNotedChangesPostRequest = $this->deserialize($restapiPhpActionWriteNotedChangesPostRequest, 'App\OpenApi\Model\RestapiPhpActionWriteNotedChangesPostRequest', $inputFormat);
        } catch (SerializerRuntimeException $exception) {
            return $this->createBadRequestResponse($exception->getMessage());
        }

        // Validate the input values
        $asserts = [];
        $asserts[] = new Assert\NotNull();
        $asserts[] = new Assert\Type('App\OpenApi\Model\RestapiPhpActionWriteNotedChangesPostRequest');
        $asserts[] = new Assert\Valid();
        $response = $this->validate($restapiPhpActionWriteNotedChangesPostRequest, $asserts);
        if ($response instanceof Response) {
            return $response;
        }


        try {
            $handler = $this->getApiHandler();


            // Make the call to the business logic
            $responseCode = 200;
            $responseHeaders = [];

            $result = $handler->restapiPhpactionwriteNotedChangesPost($restapiPhpActionWriteNotedChangesPostRequest, $responseCode, $responseHeaders);

            $message = match($responseCode) {
                200 => 'Termin erfolgreich als gelesen markiert',
                500 => 'Eintrag konnte nicht gespeichert werden',
                default => '',
            };

            return new Response(
                $result !== null ?$this->serialize($result, $responseFormat):'',
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-OpenAPI-Message' => $message
                    ]
                )
            );
        } catch (\Throwable $fallthrough) {
            return $this->createErrorResponse(new HttpException(500, 'An unsuspected error occurred.', $fallthrough));
        }
    }

    /**
     * Returns the handler for this API controller.
     * @return CalendarApiInterface
     */
    public function getApiHandler()
    {
        return $this->apiServer->getApiHandler('calendar');
    }
}
