<?php

/**
 * ClassController
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi\Controller
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App API
 *
 * REST API für die Klassenverwaltung und Stundenplan-Verwaltung
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\OpenApi\Controller;

use \Exception;
use JMS\Serializer\Exception\RuntimeException as SerializerRuntimeException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Symfony\Component\Validator\Constraints as Assert;
use App\OpenApi\Api\ClassApiInterface;
use App\OpenApi\Model\Error;
use App\OpenApi\Model\ModelClass;
use App\OpenApi\Model\RestapiPhpActionGetClassByIdGet401Response;
use App\OpenApi\Model\RestapiPhpActionUpdateClassIdIdPut200Response;
use App\OpenApi\Model\RestapiPhpActionUpdateClassIdIdPutRequest;
use App\OpenApi\Model\RestapiPhpActionWriteClassPost201Response;
use App\OpenApi\Model\RestapiPhpActionWriteClassPostRequest;

/**
 * ClassController Class Doc Comment
 *
 * @category Class
 * @package  App\OpenApi\Controller
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
class ClassController extends Controller
{

    /**
     * Operation restapiPhpactiondeleteClassididDelete
     *
     * Klasse löschen
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function restapiPhpactiondeleteClassididDeleteAction(Request $request, $id)
    {
        // Figure out what data format to return to the client
        $produces = ['application/json'];
        // Figure out what the client accepts
        $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
        $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
        if ($responseFormat === null) {
            return new Response('', 406);
        }

        // Handle authentication

        // Read out all input parameter values into variables

        // Use the default value if no value was provided

        // Deserialize the input values that needs it
        try {
            $id = $this->deserialize($id, 'string', 'string');
        } catch (SerializerRuntimeException $exception) {
            return $this->createBadRequestResponse($exception->getMessage());
        }

        // Validate the input values
        $asserts = [];
        $asserts[] = new Assert\NotNull();
        $asserts[] = new Assert\Type('string');
        $response = $this->validate($id, $asserts);
        if ($response instanceof Response) {
            return $response;
        }


        try {
            $handler = $this->getApiHandler();


            // Make the call to the business logic
            $responseCode = 200;
            $responseHeaders = [];

            $result = $handler->restapiPhpactiondeleteClassididDelete($id, $responseCode, $responseHeaders);

            $message = match($responseCode) {
                200 => 'Klasse erfolgreich gelöscht',
                400 => 'ID fehlt',
                403 => 'Keine Admin-Berechtigung oder DummyKlasse darf nicht gelöscht werden',
                404 => 'Klasse existiert nicht',
                default => '',
            };

            return new Response(
                $result !== null ?$this->serialize($result, $responseFormat):'',
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-OpenAPI-Message' => $message
                    ]
                )
            );
        } catch (\Throwable $fallthrough) {
            return $this->createErrorResponse(new HttpException(500, 'An unsuspected error occurred.', $fallthrough));
        }
    }

    /**
     * Operation restapiPhpactiongetClassByIdGet
     *
     * Klasse des Benutzers abrufen
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function restapiPhpactiongetClassByIdGetAction(Request $request)
    {
        // Figure out what data format to return to the client
        $produces = ['application/json'];
        // Figure out what the client accepts
        $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
        $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
        if ($responseFormat === null) {
            return new Response('', 406);
        }

        // Handle authentication

        // Read out all input parameter values into variables

        // Use the default value if no value was provided

        // Validate the input values


        try {
            $handler = $this->getApiHandler();


            // Make the call to the business logic
            $responseCode = 200;
            $responseHeaders = [];

            $result = $handler->restapiPhpactiongetClassByIdGet($responseCode, $responseHeaders);

            $message = match($responseCode) {
                200 => 'Klasse erfolgreich abgerufen',
                401 => 'Nicht autorisiert',
                default => '',
            };

            return new Response(
                $result !== null ?$this->serialize($result, $responseFormat):'',
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-OpenAPI-Message' => $message
                    ]
                )
            );
        } catch (\Throwable $fallthrough) {
            return $this->createErrorResponse(new HttpException(500, 'An unsuspected error occurred.', $fallthrough));
        }
    }

    /**
     * Operation restapiPhpactiongetClassGet
     *
     * Alle Klassen abrufen
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function restapiPhpactiongetClassGetAction(Request $request)
    {
        // Figure out what data format to return to the client
        $produces = ['application/json'];
        // Figure out what the client accepts
        $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
        $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
        if ($responseFormat === null) {
            return new Response('', 406);
        }

        // Handle authentication

        // Read out all input parameter values into variables

        // Use the default value if no value was provided

        // Validate the input values


        try {
            $handler = $this->getApiHandler();


            // Make the call to the business logic
            $responseCode = 200;
            $responseHeaders = [];

            $result = $handler->restapiPhpactiongetClassGet($responseCode, $responseHeaders);

            $message = match($responseCode) {
                200 => 'Klassen erfolgreich abgerufen',
                default => '',
            };

            return new Response(
                $result !== null ?$this->serialize($result, $responseFormat):'',
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-OpenAPI-Message' => $message
                    ]
                )
            );
        } catch (\Throwable $fallthrough) {
            return $this->createErrorResponse(new HttpException(500, 'An unsuspected error occurred.', $fallthrough));
        }
    }

    /**
     * Operation restapiPhpactionupdateClassididPut
     *
     * Klasse aktualisieren
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function restapiPhpactionupdateClassididPutAction(Request $request, $id)
    {
        // Make sure that the client is providing something that we can consume
        $consumes = ['application/json'];
        if (!static::isContentTypeAllowed($request, $consumes)) {
            // We can't consume the content that the client is sending us
            return new Response('', 415);
        }

        // Figure out what data format to return to the client
        $produces = ['application/json'];
        // Figure out what the client accepts
        $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
        $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
        if ($responseFormat === null) {
            return new Response('', 406);
        }

        // Handle authentication

        // Read out all input parameter values into variables
        $restapiPhpActionUpdateClassIdIdPutRequest = $request->getContent();

        // Use the default value if no value was provided

        // Deserialize the input values that needs it
        try {
            $id = $this->deserialize($id, 'string', 'string');
            $inputFormat = $request->getMimeType($request->getContentTypeFormat());
            $restapiPhpActionUpdateClassIdIdPutRequest = $this->deserialize($restapiPhpActionUpdateClassIdIdPutRequest, 'App\OpenApi\Model\RestapiPhpActionUpdateClassIdIdPutRequest', $inputFormat);
        } catch (SerializerRuntimeException $exception) {
            return $this->createBadRequestResponse($exception->getMessage());
        }

        // Validate the input values
        $asserts = [];
        $asserts[] = new Assert\NotNull();
        $asserts[] = new Assert\Type('string');
        $response = $this->validate($id, $asserts);
        if ($response instanceof Response) {
            return $response;
        }
        $asserts = [];
        $asserts[] = new Assert\NotNull();
        $asserts[] = new Assert\Type('App\OpenApi\Model\RestapiPhpActionUpdateClassIdIdPutRequest');
        $asserts[] = new Assert\Valid();
        $response = $this->validate($restapiPhpActionUpdateClassIdIdPutRequest, $asserts);
        if ($response instanceof Response) {
            return $response;
        }


        try {
            $handler = $this->getApiHandler();


            // Make the call to the business logic
            $responseCode = 200;
            $responseHeaders = [];

            $result = $handler->restapiPhpactionupdateClassididPut($id, $restapiPhpActionUpdateClassIdIdPutRequest, $responseCode, $responseHeaders);

            $message = match($responseCode) {
                200 => 'Klasse erfolgreich aktualisiert',
                400 => 'ID fehlt',
                default => '',
            };

            return new Response(
                $result !== null ?$this->serialize($result, $responseFormat):'',
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-OpenAPI-Message' => $message
                    ]
                )
            );
        } catch (\Throwable $fallthrough) {
            return $this->createErrorResponse(new HttpException(500, 'An unsuspected error occurred.', $fallthrough));
        }
    }

    /**
     * Operation restapiPhpactionwriteClassPost
     *
     * Neue Klasse erstellen
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function restapiPhpactionwriteClassPostAction(Request $request)
    {
        // Make sure that the client is providing something that we can consume
        $consumes = ['application/json'];
        if (!static::isContentTypeAllowed($request, $consumes)) {
            // We can't consume the content that the client is sending us
            return new Response('', 415);
        }

        // Figure out what data format to return to the client
        $produces = ['application/json'];
        // Figure out what the client accepts
        $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
        $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
        if ($responseFormat === null) {
            return new Response('', 406);
        }

        // Handle authentication

        // Read out all input parameter values into variables
        $restapiPhpActionWriteClassPostRequest = $request->getContent();

        // Use the default value if no value was provided

        // Deserialize the input values that needs it
        try {
            $inputFormat = $request->getMimeType($request->getContentTypeFormat());
            $restapiPhpActionWriteClassPostRequest = $this->deserialize($restapiPhpActionWriteClassPostRequest, 'App\OpenApi\Model\RestapiPhpActionWriteClassPostRequest', $inputFormat);
        } catch (SerializerRuntimeException $exception) {
            return $this->createBadRequestResponse($exception->getMessage());
        }

        // Validate the input values
        $asserts = [];
        $asserts[] = new Assert\NotNull();
        $asserts[] = new Assert\Type('App\OpenApi\Model\RestapiPhpActionWriteClassPostRequest');
        $asserts[] = new Assert\Valid();
        $response = $this->validate($restapiPhpActionWriteClassPostRequest, $asserts);
        if ($response instanceof Response) {
            return $response;
        }


        try {
            $handler = $this->getApiHandler();


            // Make the call to the business logic
            $responseCode = 200;
            $responseHeaders = [];

            $result = $handler->restapiPhpactionwriteClassPost($restapiPhpActionWriteClassPostRequest, $responseCode, $responseHeaders);

            $message = match($responseCode) {
                201 => 'Klasse erfolgreich erstellt',
                400 => 'Klassenname ist erforderlich',
                default => '',
            };

            return new Response(
                $result !== null ?$this->serialize($result, $responseFormat):'',
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-OpenAPI-Message' => $message
                    ]
                )
            );
        } catch (\Throwable $fallthrough) {
            return $this->createErrorResponse(new HttpException(500, 'An unsuspected error occurred.', $fallthrough));
        }
    }

    /**
     * Returns the handler for this API controller.
     * @return ClassApiInterface
     */
    public function getApiHandler()
    {
        return $this->apiServer->getApiHandler('class');
    }
}
