<?php

/**
 * PasswordController
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi\Controller
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App API
 *
 * REST API für die Klassenverwaltung und Stundenplan-Verwaltung
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\OpenApi\Controller;

use \Exception;
use JMS\Serializer\Exception\RuntimeException as SerializerRuntimeException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Symfony\Component\Validator\Constraints as Assert;
use App\OpenApi\Api\PasswordApiInterface;
use App\OpenApi\Model\RestapiPhpActionGetClassByIdGet401Response;
use App\OpenApi\Model\RestapiPhpActionRequestPasswordResetPost200Response;
use App\OpenApi\Model\RestapiPhpActionRequestPasswordResetPostRequest;
use App\OpenApi\Model\RestapiPhpActionResetPasswordPostRequest;

/**
 * PasswordController Class Doc Comment
 *
 * @category Class
 * @package  App\OpenApi\Controller
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
class PasswordController extends Controller
{

    /**
     * Operation restapiPhpactionrequestPasswordResetPost
     *
     * Passwort-Reset anfordern
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function restapiPhpactionrequestPasswordResetPostAction(Request $request)
    {
        // Make sure that the client is providing something that we can consume
        $consumes = ['application/json'];
        if (!static::isContentTypeAllowed($request, $consumes)) {
            // We can't consume the content that the client is sending us
            return new Response('', 415);
        }

        // Figure out what data format to return to the client
        $produces = ['application/json'];
        // Figure out what the client accepts
        $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
        $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
        if ($responseFormat === null) {
            return new Response('', 406);
        }

        // Handle authentication

        // Read out all input parameter values into variables
        $restapiPhpActionRequestPasswordResetPostRequest = $request->getContent();

        // Use the default value if no value was provided

        // Deserialize the input values that needs it
        try {
            $inputFormat = $request->getMimeType($request->getContentTypeFormat());
            $restapiPhpActionRequestPasswordResetPostRequest = $this->deserialize($restapiPhpActionRequestPasswordResetPostRequest, 'App\OpenApi\Model\RestapiPhpActionRequestPasswordResetPostRequest', $inputFormat);
        } catch (SerializerRuntimeException $exception) {
            return $this->createBadRequestResponse($exception->getMessage());
        }

        // Validate the input values
        $asserts = [];
        $asserts[] = new Assert\NotNull();
        $asserts[] = new Assert\Type('App\OpenApi\Model\RestapiPhpActionRequestPasswordResetPostRequest');
        $asserts[] = new Assert\Valid();
        $response = $this->validate($restapiPhpActionRequestPasswordResetPostRequest, $asserts);
        if ($response instanceof Response) {
            return $response;
        }


        try {
            $handler = $this->getApiHandler();


            // Make the call to the business logic
            $responseCode = 200;
            $responseHeaders = [];

            $result = $handler->restapiPhpactionrequestPasswordResetPost($restapiPhpActionRequestPasswordResetPostRequest, $responseCode, $responseHeaders);

            $message = match($responseCode) {
                200 => 'Reset-Link wurde gesendet',
                400 => 'Ungültige E-Mail',
                404 => 'E-Mail nicht gefunden',
                default => '',
            };

            return new Response(
                $result !== null ?$this->serialize($result, $responseFormat):'',
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-OpenAPI-Message' => $message
                    ]
                )
            );
        } catch (\Throwable $fallthrough) {
            return $this->createErrorResponse(new HttpException(500, 'An unsuspected error occurred.', $fallthrough));
        }
    }

    /**
     * Operation restapiPhpactionresetPasswordPost
     *
     * Passwort zurücksetzen
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function restapiPhpactionresetPasswordPostAction(Request $request)
    {
        // Make sure that the client is providing something that we can consume
        $consumes = ['application/json'];
        if (!static::isContentTypeAllowed($request, $consumes)) {
            // We can't consume the content that the client is sending us
            return new Response('', 415);
        }

        // Figure out what data format to return to the client
        $produces = ['application/json'];
        // Figure out what the client accepts
        $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
        $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
        if ($responseFormat === null) {
            return new Response('', 406);
        }

        // Handle authentication

        // Read out all input parameter values into variables
        $restapiPhpActionResetPasswordPostRequest = $request->getContent();

        // Use the default value if no value was provided

        // Deserialize the input values that needs it
        try {
            $inputFormat = $request->getMimeType($request->getContentTypeFormat());
            $restapiPhpActionResetPasswordPostRequest = $this->deserialize($restapiPhpActionResetPasswordPostRequest, 'App\OpenApi\Model\RestapiPhpActionResetPasswordPostRequest', $inputFormat);
        } catch (SerializerRuntimeException $exception) {
            return $this->createBadRequestResponse($exception->getMessage());
        }

        // Validate the input values
        $asserts = [];
        $asserts[] = new Assert\NotNull();
        $asserts[] = new Assert\Type('App\OpenApi\Model\RestapiPhpActionResetPasswordPostRequest');
        $asserts[] = new Assert\Valid();
        $response = $this->validate($restapiPhpActionResetPasswordPostRequest, $asserts);
        if ($response instanceof Response) {
            return $response;
        }


        try {
            $handler = $this->getApiHandler();


            // Make the call to the business logic
            $responseCode = 200;
            $responseHeaders = [];

            $result = $handler->restapiPhpactionresetPasswordPost($restapiPhpActionResetPasswordPostRequest, $responseCode, $responseHeaders);

            $message = match($responseCode) {
                200 => 'Passwort erfolgreich aktualisiert',
                400 => 'Ungültige Daten',
                401 => 'Token ungültig oder abgelaufen',
                default => '',
            };

            return new Response(
                $result !== null ?$this->serialize($result, $responseFormat):'',
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-OpenAPI-Message' => $message
                    ]
                )
            );
        } catch (\Throwable $fallthrough) {
            return $this->createErrorResponse(new HttpException(500, 'An unsuspected error occurred.', $fallthrough));
        }
    }

    /**
     * Returns the handler for this API controller.
     * @return PasswordApiInterface
     */
    public function getApiHandler()
    {
        return $this->apiServer->getApiHandler('password');
    }
}
