<?php

/**
 * UserController
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi\Controller
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App API
 *
 * REST API für die Klassenverwaltung und Stundenplan-Verwaltung
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\OpenApi\Controller;

use \Exception;
use JMS\Serializer\Exception\RuntimeException as SerializerRuntimeException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Symfony\Component\Validator\Constraints as Assert;
use App\OpenApi\Api\UserApiInterface;
use App\OpenApi\Model\ApiUsersRegisterPost200Response;
use App\OpenApi\Model\ApiUsersRegisterPost400Response;
use App\OpenApi\Model\ApiUsersRegisterPostRequest;
use App\OpenApi\Model\RestapiPhpActionGetClassByIdGet401Response;
use App\OpenApi\Model\RestapiPhpActionProfileGet200Response;
use App\OpenApi\Model\RestapiPhpActionProfileGet401Response;
use App\OpenApi\Model\RestapiPhpActionUpdateProfilePut200Response;
use App\OpenApi\Model\RestapiPhpActionUpdateProfilePutRequest;
use App\OpenApi\Model\User;

/**
 * UserController Class Doc Comment
 *
 * @category Class
 * @package  App\OpenApi\Controller
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
class UserController extends Controller
{

    /**
     * Operation apiUsersRegisterPost
     *
     * Neuen Benutzer registrieren
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function apiUsersRegisterPostAction(Request $request)
    {
        // Make sure that the client is providing something that we can consume
        $consumes = ['application/json'];
        if (!static::isContentTypeAllowed($request, $consumes)) {
            // We can't consume the content that the client is sending us
            return new Response('', 415);
        }

        // Figure out what data format to return to the client
        $produces = ['application/json'];
        // Figure out what the client accepts
        $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
        $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
        if ($responseFormat === null) {
            return new Response('', 406);
        }

        // Handle authentication

        // Read out all input parameter values into variables
        $apiUsersRegisterPostRequest = $request->getContent();

        // Use the default value if no value was provided

        // Deserialize the input values that needs it
        try {
            $inputFormat = $request->getMimeType($request->getContentTypeFormat());
            $apiUsersRegisterPostRequest = $this->deserialize($apiUsersRegisterPostRequest, 'App\OpenApi\Model\ApiUsersRegisterPostRequest', $inputFormat);
        } catch (SerializerRuntimeException $exception) {
            return $this->createBadRequestResponse($exception->getMessage());
        }

        // Validate the input values
        $asserts = [];
        $asserts[] = new Assert\NotNull();
        $asserts[] = new Assert\Type('App\OpenApi\Model\ApiUsersRegisterPostRequest');
        $asserts[] = new Assert\Valid();
        $response = $this->validate($apiUsersRegisterPostRequest, $asserts);
        if ($response instanceof Response) {
            return $response;
        }


        try {
            $handler = $this->getApiHandler();


            // Make the call to the business logic
            $responseCode = 200;
            $responseHeaders = [];

            $result = $handler->apiUsersRegisterPost($apiUsersRegisterPostRequest, $responseCode, $responseHeaders);

            $message = match($responseCode) {
                200 => 'Benutzer erfolgreich registriert',
                400 => 'Fehlende Registrierungsdaten',
                default => '',
            };

            return new Response(
                $result !== null ?$this->serialize($result, $responseFormat):'',
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-OpenAPI-Message' => $message
                    ]
                )
            );
        } catch (\Throwable $fallthrough) {
            return $this->createErrorResponse(new HttpException(500, 'An unsuspected error occurred.', $fallthrough));
        }
    }

    /**
     * Operation restapiPhpactiongetUserGet
     *
     * Benutzer-Daten abrufen
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function restapiPhpactiongetUserGetAction(Request $request)
    {
        // Figure out what data format to return to the client
        $produces = ['application/json'];
        // Figure out what the client accepts
        $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
        $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
        if ($responseFormat === null) {
            return new Response('', 406);
        }

        // Handle authentication

        // Read out all input parameter values into variables

        // Use the default value if no value was provided

        // Validate the input values


        try {
            $handler = $this->getApiHandler();


            // Make the call to the business logic
            $responseCode = 200;
            $responseHeaders = [];

            $result = $handler->restapiPhpactiongetUserGet($responseCode, $responseHeaders);

            $message = match($responseCode) {
                200 => 'Benutzer-Daten erfolgreich abgerufen',
                401 => 'Nicht eingeloggt',
                default => '',
            };

            return new Response(
                $result !== null ?$this->serialize($result, $responseFormat):'',
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-OpenAPI-Message' => $message
                    ]
                )
            );
        } catch (\Throwable $fallthrough) {
            return $this->createErrorResponse(new HttpException(500, 'An unsuspected error occurred.', $fallthrough));
        }
    }

    /**
     * Operation restapiPhpactionprofileGet
     *
     * Profil des Benutzers abrufen
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function restapiPhpactionprofileGetAction(Request $request)
    {
        // Figure out what data format to return to the client
        $produces = ['application/json'];
        // Figure out what the client accepts
        $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
        $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
        if ($responseFormat === null) {
            return new Response('', 406);
        }

        // Handle authentication

        // Read out all input parameter values into variables

        // Use the default value if no value was provided

        // Validate the input values


        try {
            $handler = $this->getApiHandler();


            // Make the call to the business logic
            $responseCode = 200;
            $responseHeaders = [];

            $result = $handler->restapiPhpactionprofileGet($responseCode, $responseHeaders);

            $message = match($responseCode) {
                200 => 'Profildaten erfolgreich abgerufen',
                401 => 'Nicht authentifiziert',
                404 => 'Benutzer nicht gefunden',
                default => '',
            };

            return new Response(
                $result !== null ?$this->serialize($result, $responseFormat):'',
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-OpenAPI-Message' => $message
                    ]
                )
            );
        } catch (\Throwable $fallthrough) {
            return $this->createErrorResponse(new HttpException(500, 'An unsuspected error occurred.', $fallthrough));
        }
    }

    /**
     * Operation restapiPhpactionupdateProfilePut
     *
     * Benutzer-Profil aktualisieren
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function restapiPhpactionupdateProfilePutAction(Request $request)
    {
        // Make sure that the client is providing something that we can consume
        $consumes = ['application/json'];
        if (!static::isContentTypeAllowed($request, $consumes)) {
            // We can't consume the content that the client is sending us
            return new Response('', 415);
        }

        // Figure out what data format to return to the client
        $produces = ['application/json'];
        // Figure out what the client accepts
        $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
        $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
        if ($responseFormat === null) {
            return new Response('', 406);
        }

        // Handle authentication

        // Read out all input parameter values into variables
        $restapiPhpActionUpdateProfilePutRequest = $request->getContent();

        // Use the default value if no value was provided

        // Deserialize the input values that needs it
        try {
            $inputFormat = $request->getMimeType($request->getContentTypeFormat());
            $restapiPhpActionUpdateProfilePutRequest = $this->deserialize($restapiPhpActionUpdateProfilePutRequest, 'App\OpenApi\Model\RestapiPhpActionUpdateProfilePutRequest', $inputFormat);
        } catch (SerializerRuntimeException $exception) {
            return $this->createBadRequestResponse($exception->getMessage());
        }

        // Validate the input values
        $asserts = [];
        $asserts[] = new Assert\NotNull();
        $asserts[] = new Assert\Type('App\OpenApi\Model\RestapiPhpActionUpdateProfilePutRequest');
        $asserts[] = new Assert\Valid();
        $response = $this->validate($restapiPhpActionUpdateProfilePutRequest, $asserts);
        if ($response instanceof Response) {
            return $response;
        }


        try {
            $handler = $this->getApiHandler();


            // Make the call to the business logic
            $responseCode = 200;
            $responseHeaders = [];

            $result = $handler->restapiPhpactionupdateProfilePut($restapiPhpActionUpdateProfilePutRequest, $responseCode, $responseHeaders);

            $message = match($responseCode) {
                200 => 'Profil erfolgreich aktualisiert',
                400 => 'Validierungsfehler',
                401 => 'Nicht authentifiziert',
                default => '',
            };

            return new Response(
                $result !== null ?$this->serialize($result, $responseFormat):'',
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-OpenAPI-Message' => $message
                    ]
                )
            );
        } catch (\Throwable $fallthrough) {
            return $this->createErrorResponse(new HttpException(500, 'An unsuspected error occurred.', $fallthrough));
        }
    }

    /**
     * Operation restapiPhpactionwriteUserPost
     *
     * Neuen Benutzer registrieren
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function restapiPhpactionwriteUserPostAction(Request $request)
    {
        // Make sure that the client is providing something that we can consume
        $consumes = ['application/json'];
        if (!static::isContentTypeAllowed($request, $consumes)) {
            // We can't consume the content that the client is sending us
            return new Response('', 415);
        }

        // Figure out what data format to return to the client
        $produces = ['application/json'];
        // Figure out what the client accepts
        $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
        $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
        if ($responseFormat === null) {
            return new Response('', 406);
        }

        // Handle authentication

        // Read out all input parameter values into variables
        $apiUsersRegisterPostRequest = $request->getContent();

        // Use the default value if no value was provided

        // Deserialize the input values that needs it
        try {
            $inputFormat = $request->getMimeType($request->getContentTypeFormat());
            $apiUsersRegisterPostRequest = $this->deserialize($apiUsersRegisterPostRequest, 'App\OpenApi\Model\ApiUsersRegisterPostRequest', $inputFormat);
        } catch (SerializerRuntimeException $exception) {
            return $this->createBadRequestResponse($exception->getMessage());
        }

        // Validate the input values
        $asserts = [];
        $asserts[] = new Assert\NotNull();
        $asserts[] = new Assert\Type('App\OpenApi\Model\ApiUsersRegisterPostRequest');
        $asserts[] = new Assert\Valid();
        $response = $this->validate($apiUsersRegisterPostRequest, $asserts);
        if ($response instanceof Response) {
            return $response;
        }


        try {
            $handler = $this->getApiHandler();


            // Make the call to the business logic
            $responseCode = 200;
            $responseHeaders = [];

            $result = $handler->restapiPhpactionwriteUserPost($apiUsersRegisterPostRequest, $responseCode, $responseHeaders);

            $message = match($responseCode) {
                200 => 'Benutzer erfolgreich registriert',
                400 => 'Fehlende Registrierungsdaten',
                default => '',
            };

            return new Response(
                $result !== null ?$this->serialize($result, $responseFormat):'',
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-OpenAPI-Message' => $message
                    ]
                )
            );
        } catch (\Throwable $fallthrough) {
            return $this->createErrorResponse(new HttpException(500, 'An unsuspected error occurred.', $fallthrough));
        }
    }

    /**
     * Returns the handler for this API controller.
     * @return UserApiInterface
     */
    public function getApiHandler()
    {
        return $this->apiServer->getApiHandler('user');
    }
}
