<?php
/**
 * ApiUsersRegisterPost400ResponseTest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App API
 *
 * REST API für die Klassenverwaltung und Stundenplan-Verwaltung
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace App\OpenApi\Tests\Model;

use App\OpenApi\Model\ApiUsersRegisterPost400Response;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

/**
 * ApiUsersRegisterPost400ResponseTest Class Doc Comment
 *
 * @category    Class
 * @description ApiUsersRegisterPost400Response
 * @package     App\OpenApi\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 * @coversDefaultClass \App\OpenApi\Model\ApiUsersRegisterPost400Response
 */
class ApiUsersRegisterPost400ResponseTest extends TestCase
{
    protected ApiUsersRegisterPost400Response|MockObject $object;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
        $this->object = $this->getMockBuilder(ApiUsersRegisterPost400Response::class)->getMockForAbstractClass();
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * @group integration
     * @small
     */
    public function testTestClassExists(): void
    {
        $this->assertTrue(class_exists(ApiUsersRegisterPost400Response::class));
        $this->assertInstanceOf(ApiUsersRegisterPost400Response::class, $this->object);
    }

    /**
     * Test attribute "benutzerAngelegt"
     *
     * @group unit
     * @small
     */
    public function testPropertyBenutzerAngelegt(): void
    {
        $this->markTestSkipped('Test for property benutzerAngelegt not implemented');
    }

    /**
     * Test attribute "grund"
     *
     * @group unit
     * @small
     */
    public function testPropertyGrund(): void
    {
        $this->markTestSkipped('Test for property grund not implemented');
    }
}
