<?php
/**
 * ChangeRecordTest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App API
 *
 * REST API für die Klassenverwaltung und Stundenplan-Verwaltung
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace App\OpenApi\Tests\Model;

use App\OpenApi\Model\ChangeRecord;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

/**
 * ChangeRecordTest Class Doc Comment
 *
 * @category    Class
 * @description ChangeRecord
 * @package     App\OpenApi\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 * @coversDefaultClass \App\OpenApi\Model\ChangeRecord
 */
class ChangeRecordTest extends TestCase
{
    protected ChangeRecord|MockObject $object;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
        $this->object = $this->getMockBuilder(ChangeRecord::class)->getMockForAbstractClass();
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * @group integration
     * @small
     */
    public function testTestClassExists(): void
    {
        $this->assertTrue(class_exists(ChangeRecord::class));
        $this->assertInstanceOf(ChangeRecord::class, $this->object);
    }

    /**
     * Test attribute "terminId"
     *
     * @group unit
     * @small
     */
    public function testPropertyTerminId(): void
    {
        $this->markTestSkipped('Test for property terminId not implemented');
    }

    /**
     * Test attribute "label"
     *
     * @group unit
     * @small
     */
    public function testPropertyLabel(): void
    {
        $this->markTestSkipped('Test for property label not implemented');
    }

    /**
     * Test attribute "summaryAlt"
     *
     * @group unit
     * @small
     */
    public function testPropertySummaryAlt(): void
    {
        $this->markTestSkipped('Test for property summaryAlt not implemented');
    }

    /**
     * Test attribute "startAlt"
     *
     * @group unit
     * @small
     */
    public function testPropertyStartAlt(): void
    {
        $this->markTestSkipped('Test for property startAlt not implemented');
    }

    /**
     * Test attribute "endAlt"
     *
     * @group unit
     * @small
     */
    public function testPropertyEndAlt(): void
    {
        $this->markTestSkipped('Test for property endAlt not implemented');
    }

    /**
     * Test attribute "locationAlt"
     *
     * @group unit
     * @small
     */
    public function testPropertyLocationAlt(): void
    {
        $this->markTestSkipped('Test for property locationAlt not implemented');
    }
}
