<?php
/**
 * RestapiPhpActionUpdateClassIdIdPut200ResponseTest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App API
 *
 * REST API für die Klassenverwaltung und Stundenplan-Verwaltung
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace App\OpenApi\Tests\Model;

use App\OpenApi\Model\RestapiPhpActionUpdateClassIdIdPut200Response;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

/**
 * RestapiPhpActionUpdateClassIdIdPut200ResponseTest Class Doc Comment
 *
 * @category    Class
 * @description RestapiPhpActionUpdateClassIdIdPut200Response
 * @package     App\OpenApi\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 * @coversDefaultClass \App\OpenApi\Model\RestapiPhpActionUpdateClassIdIdPut200Response
 */
class RestapiPhpActionUpdateClassIdIdPut200ResponseTest extends TestCase
{
    protected RestapiPhpActionUpdateClassIdIdPut200Response|MockObject $object;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
        $this->object = $this->getMockBuilder(RestapiPhpActionUpdateClassIdIdPut200Response::class)->getMockForAbstractClass();
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * @group integration
     * @small
     */
    public function testTestClassExists(): void
    {
        $this->assertTrue(class_exists(RestapiPhpActionUpdateClassIdIdPut200Response::class));
        $this->assertInstanceOf(RestapiPhpActionUpdateClassIdIdPut200Response::class, $this->object);
    }

    /**
     * Test attribute "erfolg"
     *
     * @group unit
     * @small
     */
    public function testPropertyErfolg(): void
    {
        $this->markTestSkipped('Test for property erfolg not implemented');
    }
}
