<?php
/**
 * RestapiPhpActionWriteClassPost201ResponseTest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App API
 *
 * REST API für die Klassenverwaltung und Stundenplan-Verwaltung
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace App\OpenApi\Tests\Model;

use App\OpenApi\Model\RestapiPhpActionWriteClassPost201Response;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

/**
 * RestapiPhpActionWriteClassPost201ResponseTest Class Doc Comment
 *
 * @category    Class
 * @description RestapiPhpActionWriteClassPost201Response
 * @package     App\OpenApi\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 * @coversDefaultClass \App\OpenApi\Model\RestapiPhpActionWriteClassPost201Response
 */
class RestapiPhpActionWriteClassPost201ResponseTest extends TestCase
{
    protected RestapiPhpActionWriteClassPost201Response|MockObject $object;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
        $this->object = $this->getMockBuilder(RestapiPhpActionWriteClassPost201Response::class)->getMockForAbstractClass();
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * @group integration
     * @small
     */
    public function testTestClassExists(): void
    {
        $this->assertTrue(class_exists(RestapiPhpActionWriteClassPost201Response::class));
        $this->assertInstanceOf(RestapiPhpActionWriteClassPost201Response::class, $this->object);
    }

    /**
     * Test attribute "erfolg"
     *
     * @group unit
     * @small
     */
    public function testPropertyErfolg(): void
    {
        $this->markTestSkipped('Test for property erfolg not implemented');
    }

    /**
     * Test attribute "klassenname"
     *
     * @group unit
     * @small
     */
    public function testPropertyKlassenname(): void
    {
        $this->markTestSkipped('Test for property klassenname not implemented');
    }
}
