<?php
/**
 * RestapiPhpActionWriteClassPostRequestTest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App API
 *
 * REST API für die Klassenverwaltung und Stundenplan-Verwaltung
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace App\OpenApi\Tests\Model;

use App\OpenApi\Model\RestapiPhpActionWriteClassPostRequest;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

/**
 * RestapiPhpActionWriteClassPostRequestTest Class Doc Comment
 *
 * @category    Class
 * @description RestapiPhpActionWriteClassPostRequest
 * @package     App\OpenApi\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 * @coversDefaultClass \App\OpenApi\Model\RestapiPhpActionWriteClassPostRequest
 */
class RestapiPhpActionWriteClassPostRequestTest extends TestCase
{
    protected RestapiPhpActionWriteClassPostRequest|MockObject $object;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
        $this->object = $this->getMockBuilder(RestapiPhpActionWriteClassPostRequest::class)->getMockForAbstractClass();
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * @group integration
     * @small
     */
    public function testTestClassExists(): void
    {
        $this->assertTrue(class_exists(RestapiPhpActionWriteClassPostRequest::class));
        $this->assertInstanceOf(RestapiPhpActionWriteClassPostRequest::class, $this->object);
    }

    /**
     * Test attribute "klassenname"
     *
     * @group unit
     * @small
     */
    public function testPropertyKlassenname(): void
    {
        $this->markTestSkipped('Test for property klassenname not implemented');
    }

    /**
     * Test attribute "icalLink"
     *
     * @group unit
     * @small
     */
    public function testPropertyIcalLink(): void
    {
        $this->markTestSkipped('Test for property icalLink not implemented');
    }
}
