<?php
/**
 * UserDataTest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App API
 *
 * REST API für die Klassenverwaltung und Stundenplan-Verwaltung
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace App\OpenApi\Tests\Model;

use App\OpenApi\Model\UserData;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

/**
 * UserDataTest Class Doc Comment
 *
 * @category    Class
 * @description UserData
 * @package     App\OpenApi\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 * @coversDefaultClass \App\OpenApi\Model\UserData
 */
class UserDataTest extends TestCase
{
    protected UserData|MockObject $object;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
        $this->object = $this->getMockBuilder(UserData::class)->getMockForAbstractClass();
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * @group integration
     * @small
     */
    public function testTestClassExists(): void
    {
        $this->assertTrue(class_exists(UserData::class));
        $this->assertInstanceOf(UserData::class, $this->object);
    }

    /**
     * Test attribute "benutzerId"
     *
     * @group unit
     * @small
     */
    public function testPropertyBenutzerId(): void
    {
        $this->markTestSkipped('Test for property benutzerId not implemented');
    }

    /**
     * Test attribute "name"
     *
     * @group unit
     * @small
     */
    public function testPropertyName(): void
    {
        $this->markTestSkipped('Test for property name not implemented');
    }

    /**
     * Test attribute "vorname"
     *
     * @group unit
     * @small
     */
    public function testPropertyVorname(): void
    {
        $this->markTestSkipped('Test for property vorname not implemented');
    }

    /**
     * Test attribute "email"
     *
     * @group unit
     * @small
     */
    public function testPropertyEmail(): void
    {
        $this->markTestSkipped('Test for property email not implemented');
    }

    /**
     * Test attribute "klassenId"
     *
     * @group unit
     * @small
     */
    public function testPropertyKlassenId(): void
    {
        $this->markTestSkipped('Test for property klassenId not implemented');
    }

    /**
     * Test attribute "klassenname"
     *
     * @group unit
     * @small
     */
    public function testPropertyKlassenname(): void
    {
        $this->markTestSkipped('Test for property klassenname not implemented');
    }
}
