<?php
/**
 * CalendarEvent
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App API
 *
 * REST API für die Klassenverwaltung und Stundenplan-Verwaltung
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\OpenApi\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the CalendarEvent model.
 *
 * @package App\OpenApi\Model
 * @author  OpenAPI Generator team
 */

class CalendarEvent 
{
        /**
     * Eindeutige Kennung des Termins
     *
     * @var string|null
     * @SerializedName("termin_id")
     * @Type("string")
     */
    #[Assert\Type("string")]
    protected ?string $terminId = null;

    /**
     * Titel/Zusammenfassung des Termins
     *
     * @var string|null
     * @SerializedName("summary")
     * @Type("string")
     */
    #[Assert\Type("string")]
    protected ?string $summary = null;

    /**
     * Startzeit des Termins
     *
     * @var \DateTime|null
     * @SerializedName("start")
     * @Type("DateTime")
     */
    #[Assert\Type("\DateTime")]
    protected ?\DateTime $start = null;

    /**
     * Endzeit des Termins
     *
     * @var \DateTime|null
     * @SerializedName("end")
     * @Type("DateTime")
     */
    #[Assert\Type("\DateTime")]
    protected ?\DateTime $end = null;

    /**
     * Ort des Termins
     *
     * @var string|null
     * @SerializedName("location")
     * @Type("string")
     */
    #[Assert\Type("string")]
    protected ?string $location = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        if (is_array($data)) {
            $this->terminId = array_key_exists('terminId', $data) ? $data['terminId'] : $this->terminId;
            $this->summary = array_key_exists('summary', $data) ? $data['summary'] : $this->summary;
            $this->start = array_key_exists('start', $data) ? $data['start'] : $this->start;
            $this->end = array_key_exists('end', $data) ? $data['end'] : $this->end;
            $this->location = array_key_exists('location', $data) ? $data['location'] : $this->location;
        }
    }

    /**
     * Gets terminId.
     *
     * @return string|null
     */
    public function getTerminId(): ?string
    {
        return $this->terminId;
    }

    /**
     * Sets terminId.
     *
     * @param string|null $terminId  Eindeutige Kennung des Termins
     *
     * @return $this
     */
    public function setTerminId(?string $terminId = null): self
    {
        $this->terminId = $terminId;

        return $this;
    }




    /**
     * Gets summary.
     *
     * @return string|null
     */
    public function getSummary(): ?string
    {
        return $this->summary;
    }

    /**
     * Sets summary.
     *
     * @param string|null $summary  Titel/Zusammenfassung des Termins
     *
     * @return $this
     */
    public function setSummary(?string $summary = null): self
    {
        $this->summary = $summary;

        return $this;
    }




    /**
     * Gets start.
     *
     * @return \DateTime|null
     */
    public function getStart(): ?\DateTime
    {
        return $this->start;
    }

    /**
     * Sets start.
     *
     * @param \DateTime|null $start  Startzeit des Termins
     *
     * @return $this
     */
    public function setStart(?\DateTime $start = null): self
    {
        $this->start = $start;

        return $this;
    }




    /**
     * Gets end.
     *
     * @return \DateTime|null
     */
    public function getEnd(): ?\DateTime
    {
        return $this->end;
    }

    /**
     * Sets end.
     *
     * @param \DateTime|null $end  Endzeit des Termins
     *
     * @return $this
     */
    public function setEnd(?\DateTime $end = null): self
    {
        $this->end = $end;

        return $this;
    }




    /**
     * Gets location.
     *
     * @return string|null
     */
    public function getLocation(): ?string
    {
        return $this->location;
    }

    /**
     * Sets location.
     *
     * @param string|null $location  Ort des Termins
     *
     * @return $this
     */
    public function setLocation(?string $location = null): self
    {
        $this->location = $location;

        return $this;
    }



}


