<?php
/**
 * ChangeRecord
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App API
 *
 * REST API für die Klassenverwaltung und Stundenplan-Verwaltung
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\OpenApi\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the ChangeRecord model.
 *
 * @package App\OpenApi\Model
 * @author  OpenAPI Generator team
 */

class ChangeRecord 
{
        /**
     * ID des geänderten Termins
     *
     * @var string|null
     * @SerializedName("termin_id")
     * @Type("string")
     */
    #[Assert\Type("string")]
    protected ?string $terminId = null;

    /**
     * Art der Änderung
     *
     * @var string|null
     * @SerializedName("label")
     * @Type("string")
     */
    #[Assert\Choice(['gelöscht', 'neu', 'geändert'])]
    #[Assert\Type("string")]
    protected ?string $label = null;

    /**
     * Alter Titel (bei Änderung)
     *
     * @var string|null
     * @SerializedName("summary_alt")
     * @Type("string")
     */
    #[Assert\Type("string")]
    protected ?string $summaryAlt = null;

    /**
     * Alte Startzeit (bei Änderung)
     *
     * @var \DateTime|null
     * @SerializedName("start_alt")
     * @Type("DateTime")
     */
    #[Assert\Type("\DateTime")]
    protected ?\DateTime $startAlt = null;

    /**
     * Alte Endzeit (bei Änderung)
     *
     * @var \DateTime|null
     * @SerializedName("end_alt")
     * @Type("DateTime")
     */
    #[Assert\Type("\DateTime")]
    protected ?\DateTime $endAlt = null;

    /**
     * Alter Ort (bei Änderung)
     *
     * @var string|null
     * @SerializedName("location_alt")
     * @Type("string")
     */
    #[Assert\Type("string")]
    protected ?string $locationAlt = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        if (is_array($data)) {
            $this->terminId = array_key_exists('terminId', $data) ? $data['terminId'] : $this->terminId;
            $this->label = array_key_exists('label', $data) ? $data['label'] : $this->label;
            $this->summaryAlt = array_key_exists('summaryAlt', $data) ? $data['summaryAlt'] : $this->summaryAlt;
            $this->startAlt = array_key_exists('startAlt', $data) ? $data['startAlt'] : $this->startAlt;
            $this->endAlt = array_key_exists('endAlt', $data) ? $data['endAlt'] : $this->endAlt;
            $this->locationAlt = array_key_exists('locationAlt', $data) ? $data['locationAlt'] : $this->locationAlt;
        }
    }

    /**
     * Gets terminId.
     *
     * @return string|null
     */
    public function getTerminId(): ?string
    {
        return $this->terminId;
    }

    /**
     * Sets terminId.
     *
     * @param string|null $terminId  ID des geänderten Termins
     *
     * @return $this
     */
    public function setTerminId(?string $terminId = null): self
    {
        $this->terminId = $terminId;

        return $this;
    }




    /**
     * Gets label.
     *
     * @return string|null
     */
    public function getLabel(): ?string
    {
        return $this->label;
    }

    /**
     * Sets label.
     *
     * @param string|null $label  Art der Änderung
     *
     * @return $this
     */
    public function setLabel(?string $label = null): self
    {
        $this->label = $label;

        return $this;
    }




    /**
     * Gets summaryAlt.
     *
     * @return string|null
     */
    public function getSummaryAlt(): ?string
    {
        return $this->summaryAlt;
    }

    /**
     * Sets summaryAlt.
     *
     * @param string|null $summaryAlt  Alter Titel (bei Änderung)
     *
     * @return $this
     */
    public function setSummaryAlt(?string $summaryAlt = null): self
    {
        $this->summaryAlt = $summaryAlt;

        return $this;
    }




    /**
     * Gets startAlt.
     *
     * @return \DateTime|null
     */
    public function getStartAlt(): ?\DateTime
    {
        return $this->startAlt;
    }

    /**
     * Sets startAlt.
     *
     * @param \DateTime|null $startAlt  Alte Startzeit (bei Änderung)
     *
     * @return $this
     */
    public function setStartAlt(?\DateTime $startAlt = null): self
    {
        $this->startAlt = $startAlt;

        return $this;
    }




    /**
     * Gets endAlt.
     *
     * @return \DateTime|null
     */
    public function getEndAlt(): ?\DateTime
    {
        return $this->endAlt;
    }

    /**
     * Sets endAlt.
     *
     * @param \DateTime|null $endAlt  Alte Endzeit (bei Änderung)
     *
     * @return $this
     */
    public function setEndAlt(?\DateTime $endAlt = null): self
    {
        $this->endAlt = $endAlt;

        return $this;
    }




    /**
     * Gets locationAlt.
     *
     * @return string|null
     */
    public function getLocationAlt(): ?string
    {
        return $this->locationAlt;
    }

    /**
     * Sets locationAlt.
     *
     * @param string|null $locationAlt  Alter Ort (bei Änderung)
     *
     * @return $this
     */
    public function setLocationAlt(?string $locationAlt = null): self
    {
        $this->locationAlt = $locationAlt;

        return $this;
    }



}


