<?php
/**
 * ModelClass
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App API
 *
 * REST API für die Klassenverwaltung und Stundenplan-Verwaltung
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\OpenApi\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the ModelClass model.
 *
 * @package App\OpenApi\Model
 * @author  OpenAPI Generator team
 */

class ModelClass 
{
        /**
     * Eindeutige Kennung der Klasse
     *
     * @var int|null
     * @SerializedName("klassen_id")
     * @Type("int")
     */
    #[Assert\Type("int")]
    protected ?int $klassenId = null;

    /**
     * Name der Klasse
     *
     * @var string|null
     * @SerializedName("klassenname")
     * @Type("string")
     */
    #[Assert\Type("string")]
    protected ?string $klassenname = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        if (is_array($data)) {
            $this->klassenId = array_key_exists('klassenId', $data) ? $data['klassenId'] : $this->klassenId;
            $this->klassenname = array_key_exists('klassenname', $data) ? $data['klassenname'] : $this->klassenname;
        }
    }

    /**
     * Gets klassenId.
     *
     * @return int|null
     */
    public function getKlassenId(): ?int
    {
        return $this->klassenId;
    }

    /**
     * Sets klassenId.
     *
     * @param int|null $klassenId  Eindeutige Kennung der Klasse
     *
     * @return $this
     */
    public function setKlassenId(?int $klassenId = null): self
    {
        $this->klassenId = $klassenId;

        return $this;
    }




    /**
     * Gets klassenname.
     *
     * @return string|null
     */
    public function getKlassenname(): ?string
    {
        return $this->klassenname;
    }

    /**
     * Sets klassenname.
     *
     * @param string|null $klassenname  Name der Klasse
     *
     * @return $this
     */
    public function setKlassenname(?string $klassenname = null): self
    {
        $this->klassenname = $klassenname;

        return $this;
    }



}


