<?php
/**
 * NotedChange
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App API
 *
 * REST API für die Klassenverwaltung und Stundenplan-Verwaltung
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\OpenApi\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the NotedChange model.
 *
 * @package App\OpenApi\Model
 * @author  OpenAPI Generator team
 */

class NotedChange 
{
        /**
     * ID des gelesenen Termins
     *
     * @var string|null
     * @SerializedName("termin_id")
     * @Type("string")
     */
    #[Assert\Type("string")]
    protected ?string $terminId = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        if (is_array($data)) {
            $this->terminId = array_key_exists('terminId', $data) ? $data['terminId'] : $this->terminId;
        }
    }

    /**
     * Gets terminId.
     *
     * @return string|null
     */
    public function getTerminId(): ?string
    {
        return $this->terminId;
    }

    /**
     * Sets terminId.
     *
     * @param string|null $terminId  ID des gelesenen Termins
     *
     * @return $this
     */
    public function setTerminId(?string $terminId = null): self
    {
        $this->terminId = $terminId;

        return $this;
    }



}


