<?php
/**
 * RestapiPhpActionUpdateClassIdIdPutRequest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App API
 *
 * REST API für die Klassenverwaltung und Stundenplan-Verwaltung
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\OpenApi\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the RestapiPhpActionUpdateClassIdIdPutRequest model.
 *
 * @package App\OpenApi\Model
 * @author  OpenAPI Generator team
 */

class RestapiPhpActionUpdateClassIdIdPutRequest 
{
        /**
     * Neuer Klassenname
     *
     * @var string|null
     * @SerializedName("klassenname")
     * @Type("string")
     */
    #[Assert\Type("string")]
    protected ?string $klassenname = null;

    /**
     * Neuer iCal-Link
     *
     * @var string|null
     * @SerializedName("ical_link")
     * @Type("string")
     */
    #[Assert\Type("string")]
    protected ?string $icalLink = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        if (is_array($data)) {
            $this->klassenname = array_key_exists('klassenname', $data) ? $data['klassenname'] : $this->klassenname;
            $this->icalLink = array_key_exists('icalLink', $data) ? $data['icalLink'] : $this->icalLink;
        }
    }

    /**
     * Gets klassenname.
     *
     * @return string|null
     */
    public function getKlassenname(): ?string
    {
        return $this->klassenname;
    }

    /**
     * Sets klassenname.
     *
     * @param string|null $klassenname  Neuer Klassenname
     *
     * @return $this
     */
    public function setKlassenname(?string $klassenname = null): self
    {
        $this->klassenname = $klassenname;

        return $this;
    }




    /**
     * Gets icalLink.
     *
     * @return string|null
     */
    public function getIcalLink(): ?string
    {
        return $this->icalLink;
    }

    /**
     * Sets icalLink.
     *
     * @param string|null $icalLink  Neuer iCal-Link
     *
     * @return $this
     */
    public function setIcalLink(?string $icalLink = null): self
    {
        $this->icalLink = $icalLink;

        return $this;
    }



}


