<?php
/**
 * RestapiPhpActionUpdateProfilePut200Response
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App API
 *
 * REST API für die Klassenverwaltung und Stundenplan-Verwaltung
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\OpenApi\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the RestapiPhpActionUpdateProfilePut200Response model.
 *
 * @package App\OpenApi\Model
 * @author  OpenAPI Generator team
 */

class RestapiPhpActionUpdateProfilePut200Response 
{
        /**
     * @var bool|null
     * @SerializedName("success")
     * @Type("bool")
     */
    #[Assert\Type("bool")]
    protected ?bool $success = null;

    /**
     * @var string|null
     * @SerializedName("message")
     * @Type("string")
     */
    #[Assert\Type("string")]
    protected ?string $message = null;

    /**
     * @var UserData|null
     * @SerializedName("userData")
     * @Type("App\OpenApi\Model\UserData")
     */
    #[Assert\Type("App\OpenApi\Model\UserData")]
    protected ?UserData $userData = null;

    /**
     * @var ModelClass[]|null
     * @SerializedName("klassen")
     * @Type("array<App\OpenApi\Model\ModelClass>")
     */
    #[Assert\All([
        new Assert\Type("App\OpenApi\Model\ModelClass"),
    ])]
    protected ?array $klassen = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        if (is_array($data)) {
            $this->success = array_key_exists('success', $data) ? $data['success'] : $this->success;
            $this->message = array_key_exists('message', $data) ? $data['message'] : $this->message;
            $this->userData = array_key_exists('userData', $data) ? $data['userData'] : $this->userData;
            $this->klassen = array_key_exists('klassen', $data) ? $data['klassen'] : $this->klassen;
        }
    }

    /**
     * Gets success.
     *
     * @return bool|null
     */
    public function isSuccess(): ?bool
    {
        return $this->success;
    }

    /**
     * Sets success.
     *
     * @param bool|null $success
     *
     * @return $this
     */
    public function setSuccess(?bool $success = null): self
    {
        $this->success = $success;

        return $this;
    }




    /**
     * Gets message.
     *
     * @return string|null
     */
    public function getMessage(): ?string
    {
        return $this->message;
    }

    /**
     * Sets message.
     *
     * @param string|null $message
     *
     * @return $this
     */
    public function setMessage(?string $message = null): self
    {
        $this->message = $message;

        return $this;
    }




    /**
     * Gets userData.
     *
     * @return UserData|null
     */
    public function getUserData(): ?UserData
    {
        return $this->userData;
    }

    /**
     * Sets userData.
     *
     * @param UserData|null $userData
     *
     * @return $this
     */
    public function setUserData(?UserData $userData = null): self
    {
        $this->userData = $userData;

        return $this;
    }




    /**
     * Gets klassen.
     *
     * @return ModelClass[]|null
     */
    public function getKlassen(): ?array
    {
        return $this->klassen;
    }

    /**
     * Sets klassen.
     *
     * @param ModelClass[]|null $klassen
     *
     * @return $this
     */
    public function setKlassen(?array $klassen = null): self
    {
        $this->klassen = $klassen;

        return $this;
    }



}


