<?php
/**
 * RestapiPhpActionWriteUserPostRequest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App API
 *
 * REST API für die Klassenverwaltung und Stundenplan-Verwaltung
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\OpenApi\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the RestapiPhpActionWriteUserPostRequest model.
 *
 * @package App\OpenApi\Model
 * @author  OpenAPI Generator team
 */

class RestapiPhpActionWriteUserPostRequest 
{
        /**
     * E-Mail-Adresse des Benutzers
     *
     * @var string|null
     * @SerializedName("email")
     * @Type("string")
     */
    #[Assert\NotNull]
    #[Assert\Type("string")]
    protected ?string $email = null;

    /**
     * Passwort des Benutzers
     *
     * @var string|null
     * @SerializedName("passwort")
     * @Type("string")
     */
    #[Assert\NotNull]
    #[Assert\Type("string")]
    protected ?string $passwort = null;

    /**
     * Nachname des Benutzers
     *
     * @var string|null
     * @SerializedName("name")
     * @Type("string")
     */
    #[Assert\NotNull]
    #[Assert\Type("string")]
    protected ?string $name = null;

    /**
     * Vorname des Benutzers
     *
     * @var string|null
     * @SerializedName("vorname")
     * @Type("string")
     */
    #[Assert\NotNull]
    #[Assert\Type("string")]
    protected ?string $vorname = null;

    /**
     * Klasse des Benutzers
     *
     * @var string|null
     * @SerializedName("klassenname")
     * @Type("string")
     */
    #[Assert\NotNull]
    #[Assert\Type("string")]
    protected ?string $klassenname = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        if (is_array($data)) {
            $this->email = array_key_exists('email', $data) ? $data['email'] : $this->email;
            $this->passwort = array_key_exists('passwort', $data) ? $data['passwort'] : $this->passwort;
            $this->name = array_key_exists('name', $data) ? $data['name'] : $this->name;
            $this->vorname = array_key_exists('vorname', $data) ? $data['vorname'] : $this->vorname;
            $this->klassenname = array_key_exists('klassenname', $data) ? $data['klassenname'] : $this->klassenname;
        }
    }

    /**
     * Gets email.
     *
     * @return string|null
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * Sets email.
     *
     * @param string|null $email  E-Mail-Adresse des Benutzers
     *
     * @return $this
     */
    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }




    /**
     * Gets passwort.
     *
     * @return string|null
     */
    public function getPasswort(): ?string
    {
        return $this->passwort;
    }

    /**
     * Sets passwort.
     *
     * @param string|null $passwort  Passwort des Benutzers
     *
     * @return $this
     */
    public function setPasswort(?string $passwort): self
    {
        $this->passwort = $passwort;

        return $this;
    }




    /**
     * Gets name.
     *
     * @return string|null
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets name.
     *
     * @param string|null $name  Nachname des Benutzers
     *
     * @return $this
     */
    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }




    /**
     * Gets vorname.
     *
     * @return string|null
     */
    public function getVorname(): ?string
    {
        return $this->vorname;
    }

    /**
     * Sets vorname.
     *
     * @param string|null $vorname  Vorname des Benutzers
     *
     * @return $this
     */
    public function setVorname(?string $vorname): self
    {
        $this->vorname = $vorname;

        return $this;
    }




    /**
     * Gets klassenname.
     *
     * @return string|null
     */
    public function getKlassenname(): ?string
    {
        return $this->klassenname;
    }

    /**
     * Sets klassenname.
     *
     * @param string|null $klassenname  Klasse des Benutzers
     *
     * @return $this
     */
    public function setKlassenname(?string $klassenname): self
    {
        $this->klassenname = $klassenname;

        return $this;
    }



}


