<?php
/**
 * RestapiPhpActionGetClassByIdGet401Response
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App API
 *
 * REST API für die Klassenverwaltung und Stundenplan-Verwaltung
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\OpenApi\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the RestapiPhpActionGetClassByIdGet401Response model.
 *
 * @package App\OpenApi\Model
 * @author  OpenAPI Generator team
 */

class RestapiPhpActionGetClassByIdGet401Response 
{
        /**
     * @var string|null
     * @SerializedName("error")
     * @Type("string")
     */
    #[Assert\Type("string")]
    protected ?string $error = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        if (is_array($data)) {
            $this->error = array_key_exists('error', $data) ? $data['error'] : $this->error;
        }
    }

    /**
     * Gets error.
     *
     * @return string|null
     */
    public function getError(): ?string
    {
        return $this->error;
    }

    /**
     * Sets error.
     *
     * @param string|null $error
     *
     * @return $this
     */
    public function setError(?string $error = null): self
    {
        $this->error = $error;

        return $this;
    }



}


