<?php
/**
 * RestapiPhpActionUpdateProfilePutRequest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App API
 *
 * REST API für die Klassenverwaltung und Stundenplan-Verwaltung
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\OpenApi\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the RestapiPhpActionUpdateProfilePutRequest model.
 *
 * @package App\OpenApi\Model
 * @author  OpenAPI Generator team
 */

class RestapiPhpActionUpdateProfilePutRequest 
{
        /**
     * Nachname
     *
     * @var string|null
     * @SerializedName("name")
     * @Type("string")
     */
    #[Assert\Type("string")]
    protected ?string $name = null;

    /**
     * Vorname
     *
     * @var string|null
     * @SerializedName("vorname")
     * @Type("string")
     */
    #[Assert\Type("string")]
    protected ?string $vorname = null;

    /**
     * E-Mail-Adresse
     *
     * @var string|null
     * @SerializedName("email")
     * @Type("string")
     */
    #[Assert\Type("string")]
    protected ?string $email = null;

    /**
     * Neues Passwort (optional)
     *
     * @var string|null
     * @SerializedName("passwort")
     * @Type("string")
     */
    #[Assert\Type("string")]
    protected ?string $passwort = null;

    /**
     * Passwort-Bestätigung (erforderlich, wenn passwort gesetzt)
     *
     * @var string|null
     * @SerializedName("passwort_confirm")
     * @Type("string")
     */
    #[Assert\Type("string")]
    protected ?string $passwortConfirm = null;

    /**
     * ID der neuen Klasse (optional)
     *
     * @var int|null
     * @SerializedName("klassen_id")
     * @Type("int")
     */
    #[Assert\Type("int")]
    protected ?int $klassenId = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        if (is_array($data)) {
            $this->name = array_key_exists('name', $data) ? $data['name'] : $this->name;
            $this->vorname = array_key_exists('vorname', $data) ? $data['vorname'] : $this->vorname;
            $this->email = array_key_exists('email', $data) ? $data['email'] : $this->email;
            $this->passwort = array_key_exists('passwort', $data) ? $data['passwort'] : $this->passwort;
            $this->passwortConfirm = array_key_exists('passwortConfirm', $data) ? $data['passwortConfirm'] : $this->passwortConfirm;
            $this->klassenId = array_key_exists('klassenId', $data) ? $data['klassenId'] : $this->klassenId;
        }
    }

    /**
     * Gets name.
     *
     * @return string|null
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets name.
     *
     * @param string|null $name  Nachname
     *
     * @return $this
     */
    public function setName(?string $name = null): self
    {
        $this->name = $name;

        return $this;
    }




    /**
     * Gets vorname.
     *
     * @return string|null
     */
    public function getVorname(): ?string
    {
        return $this->vorname;
    }

    /**
     * Sets vorname.
     *
     * @param string|null $vorname  Vorname
     *
     * @return $this
     */
    public function setVorname(?string $vorname = null): self
    {
        $this->vorname = $vorname;

        return $this;
    }




    /**
     * Gets email.
     *
     * @return string|null
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * Sets email.
     *
     * @param string|null $email  E-Mail-Adresse
     *
     * @return $this
     */
    public function setEmail(?string $email = null): self
    {
        $this->email = $email;

        return $this;
    }




    /**
     * Gets passwort.
     *
     * @return string|null
     */
    public function getPasswort(): ?string
    {
        return $this->passwort;
    }

    /**
     * Sets passwort.
     *
     * @param string|null $passwort  Neues Passwort (optional)
     *
     * @return $this
     */
    public function setPasswort(?string $passwort = null): self
    {
        $this->passwort = $passwort;

        return $this;
    }




    /**
     * Gets passwortConfirm.
     *
     * @return string|null
     */
    public function getPasswortConfirm(): ?string
    {
        return $this->passwortConfirm;
    }

    /**
     * Sets passwortConfirm.
     *
     * @param string|null $passwortConfirm  Passwort-Bestätigung (erforderlich, wenn passwort gesetzt)
     *
     * @return $this
     */
    public function setPasswortConfirm(?string $passwortConfirm = null): self
    {
        $this->passwortConfirm = $passwortConfirm;

        return $this;
    }




    /**
     * Gets klassenId.
     *
     * @return int|null
     */
    public function getKlassenId(): ?int
    {
        return $this->klassenId;
    }

    /**
     * Sets klassenId.
     *
     * @param int|null $klassenId  ID der neuen Klasse (optional)
     *
     * @return $this
     */
    public function setKlassenId(?int $klassenId = null): self
    {
        $this->klassenId = $klassenId;

        return $this;
    }



}


