<?php
/**
 * RestapiPhpActionWriteNotedChangesPost200Response
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App API
 *
 * REST API für die Klassenverwaltung und Stundenplan-Verwaltung
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\OpenApi\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the RestapiPhpActionWriteNotedChangesPost200Response model.
 *
 * @package App\OpenApi\Model
 * @author  OpenAPI Generator team
 */

class RestapiPhpActionWriteNotedChangesPost200Response 
{
        /**
     * @var bool|null
     * @SerializedName("aenderungen_notiert")
     * @Type("bool")
     */
    #[Assert\Type("bool")]
    protected ?bool $aenderungenNotiert = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        if (is_array($data)) {
            $this->aenderungenNotiert = array_key_exists('aenderungenNotiert', $data) ? $data['aenderungenNotiert'] : $this->aenderungenNotiert;
        }
    }

    /**
     * Gets aenderungenNotiert.
     *
     * @return bool|null
     */
    public function isAenderungenNotiert(): ?bool
    {
        return $this->aenderungenNotiert;
    }

    /**
     * Sets aenderungenNotiert.
     *
     * @param bool|null $aenderungenNotiert
     *
     * @return $this
     */
    public function setAenderungenNotiert(?bool $aenderungenNotiert = null): self
    {
        $this->aenderungenNotiert = $aenderungenNotiert;

        return $this;
    }



}


