<?php
/**
 * RestapiPhpActionResetPasswordPostRequest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App API
 *
 * REST API für die Klassenverwaltung und Stundenplan-Verwaltung
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\OpenApi\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the RestapiPhpActionResetPasswordPostRequest model.
 *
 * @package App\OpenApi\Model
 * @author  OpenAPI Generator team
 */

class RestapiPhpActionResetPasswordPostRequest 
{
        /**
     * Der Reset-Token aus der E-Mail
     *
     * @var string|null
     * @SerializedName("token")
     * @Type("string")
     */
    #[Assert\NotNull]
    #[Assert\Type("string")]
    protected ?string $token = null;

    /**
     * Das neue Passwort
     *
     * @var string|null
     * @SerializedName("password")
     * @Type("string")
     */
    #[Assert\NotNull]
    #[Assert\Type("string")]
    protected ?string $password = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        if (is_array($data)) {
            $this->token = array_key_exists('token', $data) ? $data['token'] : $this->token;
            $this->password = array_key_exists('password', $data) ? $data['password'] : $this->password;
        }
    }

    /**
     * Gets token.
     *
     * @return string|null
     */
    public function getToken(): ?string
    {
        return $this->token;
    }

    /**
     * Sets token.
     *
     * @param string|null $token  Der Reset-Token aus der E-Mail
     *
     * @return $this
     */
    public function setToken(?string $token): self
    {
        $this->token = $token;

        return $this;
    }




    /**
     * Gets password.
     *
     * @return string|null
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    /**
     * Sets password.
     *
     * @param string|null $password  Das neue Passwort
     *
     * @return $this
     */
    public function setPassword(?string $password): self
    {
        $this->password = $password;

        return $this;
    }



}


