<?php
/**
 * RestapiPhpActionWriteClassPost201Response
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App API
 *
 * REST API für die Klassenverwaltung und Stundenplan-Verwaltung
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\OpenApi\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the RestapiPhpActionWriteClassPost201Response model.
 *
 * @package App\OpenApi\Model
 * @author  OpenAPI Generator team
 */

class RestapiPhpActionWriteClassPost201Response 
{
        /**
     * @var bool|null
     * @SerializedName("erfolg")
     * @Type("bool")
     */
    #[Assert\Type("bool")]
    protected ?bool $erfolg = null;

    /**
     * @var string|null
     * @SerializedName("klassenname")
     * @Type("string")
     */
    #[Assert\Type("string")]
    protected ?string $klassenname = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        if (is_array($data)) {
            $this->erfolg = array_key_exists('erfolg', $data) ? $data['erfolg'] : $this->erfolg;
            $this->klassenname = array_key_exists('klassenname', $data) ? $data['klassenname'] : $this->klassenname;
        }
    }

    /**
     * Gets erfolg.
     *
     * @return bool|null
     */
    public function isErfolg(): ?bool
    {
        return $this->erfolg;
    }

    /**
     * Sets erfolg.
     *
     * @param bool|null $erfolg
     *
     * @return $this
     */
    public function setErfolg(?bool $erfolg = null): self
    {
        $this->erfolg = $erfolg;

        return $this;
    }




    /**
     * Gets klassenname.
     *
     * @return string|null
     */
    public function getKlassenname(): ?string
    {
        return $this->klassenname;
    }

    /**
     * Sets klassenname.
     *
     * @param string|null $klassenname
     *
     * @return $this
     */
    public function setKlassenname(?string $klassenname = null): self
    {
        $this->klassenname = $klassenname;

        return $this;
    }



}


