<?php
/**
 * User
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App API
 *
 * REST API für die Klassenverwaltung und Stundenplan-Verwaltung
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\OpenApi\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the User model.
 *
 * @package App\OpenApi\Model
 * @author  OpenAPI Generator team
 */

class User 
{
        /**
     * Eindeutige Benutzer-ID
     *
     * @var string|null
     * @SerializedName("benutzer_id")
     * @Type("string")
     */
    #[Assert\Type("string")]
    protected ?string $benutzerId = null;

    /**
     * Admin-Status des Benutzers
     *
     * @var int|null
     * @SerializedName("ist_admin")
     * @Type("int")
     */
    #[Assert\Choice([0, 1])]
    #[Assert\Type("int")]
    protected ?int $istAdmin = null;

    /**
     * Nachname des Benutzers
     *
     * @var string|null
     * @SerializedName("name")
     * @Type("string")
     */
    #[Assert\Type("string")]
    protected ?string $name = null;

    /**
     * Vorname des Benutzers
     *
     * @var string|null
     * @SerializedName("vorname")
     * @Type("string")
     */
    #[Assert\Type("string")]
    protected ?string $vorname = null;

    /**
     * E-Mail-Adresse des Benutzers
     *
     * @var string|null
     * @SerializedName("email")
     * @Type("string")
     */
    #[Assert\Type("string")]
    protected ?string $email = null;

    /**
     * Name der Klasse des Benutzers
     *
     * @var string|null
     * @SerializedName("klassenname")
     * @Type("string")
     */
    #[Assert\Type("string")]
    protected ?string $klassenname = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        if (is_array($data)) {
            $this->benutzerId = array_key_exists('benutzerId', $data) ? $data['benutzerId'] : $this->benutzerId;
            $this->istAdmin = array_key_exists('istAdmin', $data) ? $data['istAdmin'] : $this->istAdmin;
            $this->name = array_key_exists('name', $data) ? $data['name'] : $this->name;
            $this->vorname = array_key_exists('vorname', $data) ? $data['vorname'] : $this->vorname;
            $this->email = array_key_exists('email', $data) ? $data['email'] : $this->email;
            $this->klassenname = array_key_exists('klassenname', $data) ? $data['klassenname'] : $this->klassenname;
        }
    }

    /**
     * Gets benutzerId.
     *
     * @return string|null
     */
    public function getBenutzerId(): ?string
    {
        return $this->benutzerId;
    }

    /**
     * Sets benutzerId.
     *
     * @param string|null $benutzerId  Eindeutige Benutzer-ID
     *
     * @return $this
     */
    public function setBenutzerId(?string $benutzerId = null): self
    {
        $this->benutzerId = $benutzerId;

        return $this;
    }




    /**
     * Gets istAdmin.
     *
     * @return int|null
     */
    public function getIstAdmin(): ?int
    {
        return $this->istAdmin;
    }

    /**
     * Sets istAdmin.
     *
     * @param int|null $istAdmin  Admin-Status des Benutzers
     *
     * @return $this
     */
    public function setIstAdmin(?int $istAdmin = null): self
    {
        $this->istAdmin = $istAdmin;

        return $this;
    }




    /**
     * Gets name.
     *
     * @return string|null
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets name.
     *
     * @param string|null $name  Nachname des Benutzers
     *
     * @return $this
     */
    public function setName(?string $name = null): self
    {
        $this->name = $name;

        return $this;
    }




    /**
     * Gets vorname.
     *
     * @return string|null
     */
    public function getVorname(): ?string
    {
        return $this->vorname;
    }

    /**
     * Sets vorname.
     *
     * @param string|null $vorname  Vorname des Benutzers
     *
     * @return $this
     */
    public function setVorname(?string $vorname = null): self
    {
        $this->vorname = $vorname;

        return $this;
    }




    /**
     * Gets email.
     *
     * @return string|null
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * Sets email.
     *
     * @param string|null $email  E-Mail-Adresse des Benutzers
     *
     * @return $this
     */
    public function setEmail(?string $email = null): self
    {
        $this->email = $email;

        return $this;
    }




    /**
     * Gets klassenname.
     *
     * @return string|null
     */
    public function getKlassenname(): ?string
    {
        return $this->klassenname;
    }

    /**
     * Sets klassenname.
     *
     * @param string|null $klassenname  Name der Klasse des Benutzers
     *
     * @return $this
     */
    public function setKlassenname(?string $klassenname = null): self
    {
        $this->klassenname = $klassenname;

        return $this;
    }



}


