<?php
/**
 * CalendarEventTest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App Calendar API
 *
 * Symfony-konforme REST API für Stundenplan und Terminverwaltung
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace App\OpenApi\Tests\Model;

use App\OpenApi\Model\CalendarEvent;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

/**
 * CalendarEventTest Class Doc Comment
 *
 * @category    Class
 * @description Termin des Stundenplans mit optionalen Metadaten
 * @package     App\OpenApi\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 * @coversDefaultClass \App\OpenApi\Model\CalendarEvent
 */
class CalendarEventTest extends TestCase
{
    protected CalendarEvent|MockObject $object;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
        $this->object = $this->getMockBuilder(CalendarEvent::class)->getMockForAbstractClass();
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * @group integration
     * @small
     */
    public function testTestClassExists(): void
    {
        $this->assertTrue(class_exists(CalendarEvent::class));
        $this->assertInstanceOf(CalendarEvent::class, $this->object);
    }

    /**
     * Test attribute "id"
     *
     * @group unit
     * @small
     */
    public function testPropertyId(): void
    {
        $this->markTestSkipped('Test for property id not implemented');
    }

    /**
     * Test attribute "summary"
     *
     * @group unit
     * @small
     */
    public function testPropertySummary(): void
    {
        $this->markTestSkipped('Test for property summary not implemented');
    }

    /**
     * Test attribute "description"
     *
     * @group unit
     * @small
     */
    public function testPropertyDescription(): void
    {
        $this->markTestSkipped('Test for property description not implemented');
    }

    /**
     * Test attribute "start"
     *
     * @group unit
     * @small
     */
    public function testPropertyStart(): void
    {
        $this->markTestSkipped('Test for property start not implemented');
    }

    /**
     * Test attribute "end"
     *
     * @group unit
     * @small
     */
    public function testPropertyEnd(): void
    {
        $this->markTestSkipped('Test for property end not implemented');
    }

    /**
     * Test attribute "location"
     *
     * @group unit
     * @small
     */
    public function testPropertyLocation(): void
    {
        $this->markTestSkipped('Test for property location not implemented');
    }

    /**
     * Test attribute "label"
     *
     * @group unit
     * @small
     */
    public function testPropertyLabel(): void
    {
        $this->markTestSkipped('Test for property label not implemented');
    }

    /**
     * Test attribute "kategorie"
     *
     * @group unit
     * @small
     */
    public function testPropertyKategorie(): void
    {
        $this->markTestSkipped('Test for property kategorie not implemented');
    }

    /**
     * Test attribute "originalEvent"
     *
     * @group unit
     * @small
     */
    public function testPropertyOriginalEvent(): void
    {
        $this->markTestSkipped('Test for property originalEvent not implemented');
    }

    /**
     * Test attribute "updatedAt"
     *
     * @group unit
     * @small
     */
    public function testPropertyUpdatedAt(): void
    {
        $this->markTestSkipped('Test for property updatedAt not implemented');
    }
}
