<?php
/**
 * CalendarEventOriginalEventTest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App Calendar API
 *
 * Symfony-konforme REST API für Stundenplan und Terminverwaltung
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace App\OpenApi\Tests\Model;

use App\OpenApi\Model\CalendarEventOriginalEvent;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

/**
 * CalendarEventOriginalEventTest Class Doc Comment
 *
 * @category    Class
 * @description CalendarEventOriginalEvent
 * @package     App\OpenApi\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 * @coversDefaultClass \App\OpenApi\Model\CalendarEventOriginalEvent
 */
class CalendarEventOriginalEventTest extends TestCase
{
    protected CalendarEventOriginalEvent|MockObject $object;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
        $this->object = $this->getMockBuilder(CalendarEventOriginalEvent::class)->getMockForAbstractClass();
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * @group integration
     * @small
     */
    public function testTestClassExists(): void
    {
        $this->assertTrue(class_exists(CalendarEventOriginalEvent::class));
        $this->assertInstanceOf(CalendarEventOriginalEvent::class, $this->object);
    }

    /**
     * Test attribute "summary"
     *
     * @group unit
     * @small
     */
    public function testPropertySummary(): void
    {
        $this->markTestSkipped('Test for property summary not implemented');
    }

    /**
     * Test attribute "start"
     *
     * @group unit
     * @small
     */
    public function testPropertyStart(): void
    {
        $this->markTestSkipped('Test for property start not implemented');
    }

    /**
     * Test attribute "end"
     *
     * @group unit
     * @small
     */
    public function testPropertyEnd(): void
    {
        $this->markTestSkipped('Test for property end not implemented');
    }

    /**
     * Test attribute "location"
     *
     * @group unit
     * @small
     */
    public function testPropertyLocation(): void
    {
        $this->markTestSkipped('Test for property location not implemented');
    }
}
