<?php
/**
 * UserProfileTest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App Calendar API
 *
 * Symfony-konforme REST API für Stundenplan und Terminverwaltung
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace App\OpenApi\Tests\Model;

use App\OpenApi\Model\UserProfile;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

/**
 * UserProfileTest Class Doc Comment
 *
 * @category    Class
 * @description Benutzerprofil-Daten
 * @package     App\OpenApi\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 * @coversDefaultClass \App\OpenApi\Model\UserProfile
 */
class UserProfileTest extends TestCase
{
    protected UserProfile|MockObject $object;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
        $this->object = $this->getMockBuilder(UserProfile::class)->getMockForAbstractClass();
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * @group integration
     * @small
     */
    public function testTestClassExists(): void
    {
        $this->assertTrue(class_exists(UserProfile::class));
        $this->assertInstanceOf(UserProfile::class, $this->object);
    }

    /**
     * Test attribute "identityId"
     *
     * @group unit
     * @small
     */
    public function testPropertyIdentityId(): void
    {
        $this->markTestSkipped('Test for property identityId not implemented');
    }

    /**
     * Test attribute "email"
     *
     * @group unit
     * @small
     */
    public function testPropertyEmail(): void
    {
        $this->markTestSkipped('Test for property email not implemented');
    }

    /**
     * Test attribute "isAdmin"
     *
     * @group unit
     * @small
     */
    public function testPropertyIsAdmin(): void
    {
        $this->markTestSkipped('Test for property isAdmin not implemented');
    }

    /**
     * Test attribute "roles"
     *
     * @group unit
     * @small
     */
    public function testPropertyRoles(): void
    {
        $this->markTestSkipped('Test for property roles not implemented');
    }

    /**
     * Test attribute "klasse"
     *
     * @group unit
     * @small
     */
    public function testPropertyKlasse(): void
    {
        $this->markTestSkipped('Test for property klasse not implemented');
    }
}
