<?php

/**
 * CalendarController
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi\Controller
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App Calendar API
 *
 * Symfony-konforme REST API für Stundenplan und Terminverwaltung
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\OpenApi\Controller;

use \Exception;
use JMS\Serializer\Exception\RuntimeException as SerializerRuntimeException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Symfony\Component\Validator\Constraints as Assert;
use App\OpenApi\Api\CalendarApiInterface;
use App\OpenApi\Model\GetCalendar200Response;
use App\OpenApi\Model\Problem;

/**
 * CalendarController Class Doc Comment
 *
 * @category Class
 * @package  App\OpenApi\Controller
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
class CalendarController extends Controller
{

    /**
     * Operation getCalendar
     *
     * Aktuellen Stundenplan abrufen
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function getCalendarAction(Request $request)
    {
        // Figure out what data format to return to the client
        $produces = ['application/json', 'application/problem+json'];
        // Figure out what the client accepts
        $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
        $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
        if ($responseFormat === null) {
            return new Response('', 406);
        }

        // Handle authentication
        // Authentication 'BearerAuth' required
        // HTTP bearer authentication required
        $securityBearerAuth = $request->headers->get('authorization');

        // Read out all input parameter values into variables

        // Use the default value if no value was provided

        // Validate the input values


        try {
            $handler = $this->getApiHandler();

            // Set authentication method 'BearerAuth'
            $handler->setBearerAuth($securityBearerAuth);

            // Make the call to the business logic
            $responseCode = 200;
            $responseHeaders = [];

            $result = $handler->getCalendar($responseCode, $responseHeaders);

            $message = match($responseCode) {
                200 => 'Stundenplan erfolgreich abgerufen',
                0 => 'Fachlicher oder technischer Fehler',
                default => 'Fachlicher oder technischer Fehler',
            };

            return new Response(
                $result !== null ?$this->serialize($result, $responseFormat):'',
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-OpenAPI-Message' => $message
                    ]
                )
            );
        } catch (\Throwable $fallthrough) {
            return $this->createErrorResponse(new HttpException(500, 'An unsuspected error occurred.', $fallthrough));
        }
    }

    /**
     * Returns the handler for this API controller.
     * @return CalendarApiInterface
     */
    public function getApiHandler()
    {
        return $this->apiServer->getApiHandler('calendar');
    }
}
