<?php
/**
 * OpenAPIServerBundle
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App Calendar API
 *
 * Symfony-konforme REST API für Stundenplan und Terminverwaltung
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\OpenApi;

use Symfony\Component\HttpKernel\Bundle\Bundle;
// use Symfony\Component\DependencyInjection\ContainerBuilder; // Nicht mehr benötigt
// use App\OpenApi\DependencyInjection\Compiler\OpenAPIServerApiPass; // Nicht mehr benötigt

/**
 * OpenAPIServerBundle Class Doc Comment
 *
 * @category Class
 * @package  App\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
class OpenAPIServerBundle extends Bundle
{
    // Alle Methoden entfernt
}
