<?php
/**
 * CalendarApiInterfaceTest
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi\Tests\Api
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App API
 *
 * REST API für die Klassenverwaltung und Stundenplan-Verwaltung
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */

namespace App\OpenApi\Tests\Api;

use Symfony\Bundle\FrameworkBundle\KernelBrowser;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

/**
 * CalendarApiInterfaceTest Class Doc Comment
 *
 * @category Class
 * @package  App\OpenApi\Tests\Api
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 * @coversDefaultClass \App\OpenApi\Api\CalendarApiInterface
 */
class CalendarApiInterfaceTest extends WebTestCase
{
    private static ?KernelBrowser $client = null;

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
        if (null === self::$client) {
            self::$client = static::createClient();
        }
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
        static::ensureKernelShutdown();
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for restapiPhpactiongetCalendarGet
     *
     * Aktuellen Stundenplan abrufen.
     *
     */
    public function testRestapiPhpactiongetCalendarGet(): void
    {
        $client = self::$client;

        $path = '/restapi.php?action&#x3D;getCalendar';

        $crawler = $client->request('GET', $path);
        $this->markTestSkipped('Test for restapiPhpactiongetCalendarGet not implemented');
    }

    /**
     * Test case for restapiPhpactiongetChangesGet
     *
     * Terminänderungen abrufen.
     *
     */
    public function testRestapiPhpactiongetChangesGet(): void
    {
        $client = self::$client;

        $path = '/restapi.php?action&#x3D;getChanges';

        $crawler = $client->request('GET', $path);
        $this->markTestSkipped('Test for restapiPhpactiongetChangesGet not implemented');
    }

    /**
     * Test case for restapiPhpactiongetNotedChangesGet
     *
     * Gelesene Änderungen abrufen.
     *
     */
    public function testRestapiPhpactiongetNotedChangesGet(): void
    {
        $client = self::$client;

        $path = '/restapi.php?action&#x3D;getNotedChanges';

        $crawler = $client->request('GET', $path);
        $this->markTestSkipped('Test for restapiPhpactiongetNotedChangesGet not implemented');
    }

    /**
     * Test case for restapiPhpactionwriteNotedChangesPost
     *
     * Terminänderung als gelesen markieren.
     *
     */
    public function testRestapiPhpactionwriteNotedChangesPost(): void
    {
        $client = self::$client;

        $path = '/restapi.php?action&#x3D;writeNotedChanges';

        $crawler = $client->request('POST', $path, [], [], ['CONTENT_TYPE' => 'application/json']);
        $this->markTestSkipped('Test for restapiPhpactionwriteNotedChangesPost not implemented');
    }

    /**
     * @param string $regexp
     * @return mixed
     */
    protected function genTestData(string $regexp)
    {
        $grammar  = new \Hoa\File\Read('hoa://Library/Regex/Grammar.pp');
        $compiler = \Hoa\Compiler\Llk\Llk::load($grammar);
        $ast      = $compiler->parse($regexp);
        $generator = new \Hoa\Regex\Visitor\Isotropic(new \Hoa\Math\Sampler\Random());

        return $generator->visit($ast);
    }
}
