<?php
/**
 * UserProfileApiInterface
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App Calendar API
 *
 * Symfony-konforme REST API für Stundenplan und Terminverwaltung
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\OpenApi\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use App\OpenApi\Model\Problem;
use App\OpenApi\Model\UpdateKlasse200Response;
use App\OpenApi\Model\UpdateKlasseRequest;
use App\OpenApi\Model\UserProfile;

/**
 * UserProfileApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  App\OpenApi\Api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface UserProfileApiInterface
{

    /**
     * Sets authentication method BearerAuth
     *
     * @param string|null $value Value of the BearerAuth authentication method.
     *
     * @return void
     */
    public function setBearerAuth(?string $value): void;

    /**
     * Operation getUserProfile
     *
     * Aktuelles Benutzerprofil abrufen
     *
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return array|object|null
     */
    public function getUserProfile(
        int &$responseCode,
        array &$responseHeaders
    ): array|object|null;

    /**
     * Operation updateKlasse
     *
     * Klasse des Benutzers aktualisieren
     *
     * @param  UpdateKlasseRequest $updateKlasseRequest   (required)
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return array|object|null
     */
    public function updateKlasse(
        UpdateKlasseRequest $updateKlasseRequest,
        int &$responseCode,
        array &$responseHeaders
    ): array|object|null;
}
