<?php
/**
 * CalendarApiInterface
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App API
 *
 * REST API für die Klassenverwaltung und Stundenplan-Verwaltung
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\OpenApi\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use App\OpenApi\Model\CalendarEvent;
use App\OpenApi\Model\ChangeRecord;
use App\OpenApi\Model\Error;
use App\OpenApi\Model\NotedChange;
use App\OpenApi\Model\RestapiPhpActionWriteNotedChangesPost200Response;
use App\OpenApi\Model\RestapiPhpActionWriteNotedChangesPostRequest;

/**
 * CalendarApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  App\OpenApi\Api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface CalendarApiInterface
{

    /**
     * Operation restapiPhpactiongetCalendarGet
     *
     * Aktuellen Stundenplan abrufen
     *
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return array|object|null
     */
    public function restapiPhpactiongetCalendarGet(
        int &$responseCode,
        array &$responseHeaders
    ): array|object|null;

    /**
     * Operation restapiPhpactiongetChangesGet
     *
     * Terminänderungen abrufen
     *
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return array|object|null
     */
    public function restapiPhpactiongetChangesGet(
        int &$responseCode,
        array &$responseHeaders
    ): array|object|null;

    /**
     * Operation restapiPhpactiongetNotedChangesGet
     *
     * Gelesene Änderungen abrufen
     *
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return array|object|null
     */
    public function restapiPhpactiongetNotedChangesGet(
        int &$responseCode,
        array &$responseHeaders
    ): array|object|null;

    /**
     * Operation restapiPhpactionwriteNotedChangesPost
     *
     * Terminänderung als gelesen markieren
     *
     * @param  RestapiPhpActionWriteNotedChangesPostRequest $restapiPhpActionWriteNotedChangesPostRequest   (required)
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return array|object|null
     */
    public function restapiPhpactionwriteNotedChangesPost(
        RestapiPhpActionWriteNotedChangesPostRequest $restapiPhpActionWriteNotedChangesPostRequest,
        int &$responseCode,
        array &$responseHeaders
    ): array|object|null;
}
