<?php
/**
 * ClassApiInterface
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App API
 *
 * REST API für die Klassenverwaltung und Stundenplan-Verwaltung
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\OpenApi\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use App\OpenApi\Model\Error;
use App\OpenApi\Model\ModelClass;
use App\OpenApi\Model\RestapiPhpActionGetClassByIdGet401Response;
use App\OpenApi\Model\RestapiPhpActionUpdateClassIdIdPut200Response;
use App\OpenApi\Model\RestapiPhpActionUpdateClassIdIdPutRequest;
use App\OpenApi\Model\RestapiPhpActionWriteClassPost201Response;
use App\OpenApi\Model\RestapiPhpActionWriteClassPostRequest;

/**
 * ClassApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  App\OpenApi\Api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface ClassApiInterface
{

    /**
     * Operation restapiPhpactiondeleteClassididDelete
     *
     * Klasse löschen
     *
     * @param  string $id  Klassen-ID (required)
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return array|object|null
     */
    public function restapiPhpactiondeleteClassididDelete(
        string $id,
        int &$responseCode,
        array &$responseHeaders
    ): array|object|null;

    /**
     * Operation restapiPhpactiongetClassByIdGet
     *
     * Klasse des Benutzers abrufen
     *
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return array|object|null
     */
    public function restapiPhpactiongetClassByIdGet(
        int &$responseCode,
        array &$responseHeaders
    ): array|object|null;

    /**
     * Operation restapiPhpactiongetClassGet
     *
     * Alle Klassen abrufen
     *
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return array|object|null
     */
    public function restapiPhpactiongetClassGet(
        int &$responseCode,
        array &$responseHeaders
    ): array|object|null;

    /**
     * Operation restapiPhpactionupdateClassididPut
     *
     * Klasse aktualisieren
     *
     * @param  string $id  Klassen-ID (required)
     * @param  RestapiPhpActionUpdateClassIdIdPutRequest $restapiPhpActionUpdateClassIdIdPutRequest   (required)
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return array|object|null
     */
    public function restapiPhpactionupdateClassididPut(
        string $id,
        RestapiPhpActionUpdateClassIdIdPutRequest $restapiPhpActionUpdateClassIdIdPutRequest,
        int &$responseCode,
        array &$responseHeaders
    ): array|object|null;

    /**
     * Operation restapiPhpactionwriteClassPost
     *
     * Neue Klasse erstellen
     *
     * @param  RestapiPhpActionWriteClassPostRequest $restapiPhpActionWriteClassPostRequest   (required)
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return array|object|null
     */
    public function restapiPhpactionwriteClassPost(
        RestapiPhpActionWriteClassPostRequest $restapiPhpActionWriteClassPostRequest,
        int &$responseCode,
        array &$responseHeaders
    ): array|object|null;
}
