<?php
/**
 * PasswordApiInterface
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App API
 *
 * REST API für die Klassenverwaltung und Stundenplan-Verwaltung
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\OpenApi\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use App\OpenApi\Model\RestapiPhpActionGetClassByIdGet401Response;
use App\OpenApi\Model\RestapiPhpActionRequestPasswordResetPost200Response;
use App\OpenApi\Model\RestapiPhpActionRequestPasswordResetPostRequest;
use App\OpenApi\Model\RestapiPhpActionResetPasswordPostRequest;

/**
 * PasswordApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  App\OpenApi\Api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface PasswordApiInterface
{

    /**
     * Operation restapiPhpactionrequestPasswordResetPost
     *
     * Passwort-Reset anfordern
     *
     * @param  RestapiPhpActionRequestPasswordResetPostRequest $restapiPhpActionRequestPasswordResetPostRequest   (required)
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return array|object|null
     */
    public function restapiPhpactionrequestPasswordResetPost(
        RestapiPhpActionRequestPasswordResetPostRequest $restapiPhpActionRequestPasswordResetPostRequest,
        int &$responseCode,
        array &$responseHeaders
    ): array|object|null;

    /**
     * Operation restapiPhpactionresetPasswordPost
     *
     * Passwort zurücksetzen
     *
     * @param  RestapiPhpActionResetPasswordPostRequest $restapiPhpActionResetPasswordPostRequest   (required)
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return array|object|null
     */
    public function restapiPhpactionresetPasswordPost(
        RestapiPhpActionResetPasswordPostRequest $restapiPhpActionResetPasswordPostRequest,
        int &$responseCode,
        array &$responseHeaders
    ): array|object|null;
}
