<?php
/**
 * UserApiInterface
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App API
 *
 * REST API für die Klassenverwaltung und Stundenplan-Verwaltung
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\OpenApi\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use App\OpenApi\Model\ApiUsersRegisterPost200Response;
use App\OpenApi\Model\ApiUsersRegisterPost400Response;
use App\OpenApi\Model\ApiUsersRegisterPostRequest;
use App\OpenApi\Model\RestapiPhpActionGetClassByIdGet401Response;
use App\OpenApi\Model\RestapiPhpActionProfileGet200Response;
use App\OpenApi\Model\RestapiPhpActionProfileGet401Response;
use App\OpenApi\Model\RestapiPhpActionUpdateProfilePut200Response;
use App\OpenApi\Model\RestapiPhpActionUpdateProfilePutRequest;
use App\OpenApi\Model\User;

/**
 * UserApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  App\OpenApi\Api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface UserApiInterface
{

    /**
     * Operation apiUsersRegisterPost
     *
     * Neuen Benutzer registrieren
     *
     * @param  ApiUsersRegisterPostRequest $apiUsersRegisterPostRequest   (required)
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return array|object|null
     */
    public function apiUsersRegisterPost(
        ApiUsersRegisterPostRequest $apiUsersRegisterPostRequest,
        int &$responseCode,
        array &$responseHeaders
    ): array|object|null;

    /**
     * Operation restapiPhpactiongetUserGet
     *
     * Benutzer-Daten abrufen
     *
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return array|object|null
     */
    public function restapiPhpactiongetUserGet(
        int &$responseCode,
        array &$responseHeaders
    ): array|object|null;

    /**
     * Operation restapiPhpactionprofileGet
     *
     * Profil des Benutzers abrufen
     *
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return array|object|null
     */
    public function restapiPhpactionprofileGet(
        int &$responseCode,
        array &$responseHeaders
    ): array|object|null;

    /**
     * Operation restapiPhpactionupdateProfilePut
     *
     * Benutzer-Profil aktualisieren
     *
     * @param  RestapiPhpActionUpdateProfilePutRequest $restapiPhpActionUpdateProfilePutRequest   (required)
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return array|object|null
     */
    public function restapiPhpactionupdateProfilePut(
        RestapiPhpActionUpdateProfilePutRequest $restapiPhpActionUpdateProfilePutRequest,
        int &$responseCode,
        array &$responseHeaders
    ): array|object|null;

    /**
     * Operation restapiPhpactionwriteUserPost
     *
     * Neuen Benutzer registrieren
     *
     * @param  ApiUsersRegisterPostRequest $apiUsersRegisterPostRequest   (required)
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return array|object|null
     */
    public function restapiPhpactionwriteUserPost(
        ApiUsersRegisterPostRequest $apiUsersRegisterPostRequest,
        int &$responseCode,
        array &$responseHeaders
    ): array|object|null;
}
