<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260525211730 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // Entfernt: CREATE EXTENSION und CREATE TYPE Anweisungen
        // $this->addSql('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";');
        // $this->addSql("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'aenderungs_label') THEN CREATE TYPE aenderungs_label AS ENUM ('gelöscht', 'neu', 'geändert'); END IF; IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'kalender_kategorie') THEN CREATE TYPE kalender_kategorie AS ENUM ('klausur', 'bib-event', 'eigenes-event', 'unterricht', 'projekt', 'ferien', 'prüfung'); END IF; END $$;");

        // Hinzugefügt: CREATE TABLE aenderungs_label
        $this->addSql('CREATE TABLE aenderungs_label (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_23AA5C495E237E06 ON aenderungs_label (name)');

        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE benutzer (id UUID NOT NULL, passwort VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, istadmin BOOLEAN NOT NULL, roles JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_36144FC7E7927C74 ON benutzer (email)');
        // GeaenderteTermine: change_type aenderungs_label NOT NULL entfernt, ersetzt durch change_type_id INT NOT NULL und Fremdschlüssel
        $this->addSql('CREATE TABLE geaenderte_termine (id UUID NOT NULL, summary VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, start TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, "end" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, location VARCHAR(255) DEFAULT NULL, label VARCHAR(50) DEFAULT NULL, kategorie VARCHAR(50) DEFAULT NULL, original_event JSON DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, klasse VARCHAR(255) NOT NULL, change_type_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_71261E5C354B2E3A ON geaenderte_termine (change_type_id)');
        $this->addSql('CREATE TABLE klassen (klassen_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, klassenname VARCHAR(100) NOT NULL, ical_link VARCHAR(255) DEFAULT NULL, last_synced_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (klassen_id))');
        $this->addSql('CREATE TABLE persoenliche_daten (id UUID NOT NULL, name VARCHAR(100) NOT NULL, vorname VARCHAR(100) NOT NULL, benutzer_id UUID NOT NULL, klassen_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_55F38D3C9F9AC274 ON persoenliche_daten (benutzer_id)');
        $this->addSql('CREATE INDEX IDX_55F38D3C2F869492 ON persoenliche_daten (klassen_id)');
        // StundenplanAlt: kategorie kalender_kategorie DEFAULT NULL entfernt
        $this->addSql('CREATE TABLE stundenplan_alt (id UUID NOT NULL, summary VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, start TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, "end" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, location VARCHAR(255) DEFAULT NULL, label VARCHAR(50) DEFAULT NULL, original_event JSON DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, klasse VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        // StundenplanNeu: kategorie kalender_kategorie DEFAULT NULL entfernt
        $this->addSql('CREATE TABLE stundenplan_neu (id UUID NOT NULL, summary VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, start TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, "end" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, location VARCHAR(255) DEFAULT NULL, label VARCHAR(50) DEFAULT NULL, original_event JSON DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, klasse VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE stundenplan_alt ADD kategorie VARCHAR(50) DEFAULT NULL;'); // Hinzugefügt
        $this->addSql('ALTER TABLE stundenplan_neu ADD kategorie VARCHAR(50) DEFAULT NULL;'); // Hinzugefügt
        $this->addSql('ALTER TABLE geaenderte_termine ADD CONSTRAINT FK_71261E5C354B2E3A FOREIGN KEY (change_type_id) REFERENCES aenderungs_label (id) NOT DEFERRABLE'); // Fremdschlüssel hinzugefügt
        $this->addSql('ALTER TABLE persoenliche_daten ADD CONSTRAINT FK_55F38D3C9F9AC274 FOREIGN KEY (benutzer_id) REFERENCES benutzer (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE persoenliche_daten ADD CONSTRAINT FK_55F38D3C2F869492 FOREIGN KEY (klassen_id) REFERENCES klassen (klassen_id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE geaenderte_termine DROP CONSTRAINT FK_71261E5C354B2E3A'); // Fremdschlüssel entfernt
        $this->addSql('ALTER TABLE persoenliche_daten DROP CONSTRAINT FK_55F38D3C9F9AC274');
        $this->addSql('ALTER TABLE persoenliche_daten DROP CONSTRAINT FK_55F38D3C2F869492');
        $this->addSql('DROP TABLE aenderungs_label'); // Tabelle entfernt
        $this->addSql('DROP TABLE benutzer');
        $this->addSql('DROP TABLE geaenderte_termine');
        $this->addSql('DROP TABLE klassen');
        $this->addSql('DROP TABLE persoenliche_daten');
        $this->addSql('DROP TABLE stundenplan_alt');
        $this->addSql('DROP TABLE stundenplan_neu');
    }
}
