<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260524222417 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE benutzer (id UUID NOT NULL, passwort VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, istadmin BOOLEAN NOT NULL, roles JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_36144FC7E7927C74 ON benutzer (email)');
        $this->addSql('CREATE TABLE geaenderte_termine (id UUID NOT NULL, summary VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, start TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, "end" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, location VARCHAR(255) DEFAULT NULL, label VARCHAR(50) DEFAULT NULL, kategorie VARCHAR(50) DEFAULT NULL, original_event JSON DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, klasse VARCHAR(255) NOT NULL, change_type aenderungs_label NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE klassen (klassen_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, klassenname VARCHAR(100) NOT NULL, ical_link VARCHAR(255) DEFAULT NULL, last_synced_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (klassen_id))');
        $this->addSql('CREATE TABLE persoenliche_daten (id UUID NOT NULL, name VARCHAR(100) NOT NULL, vorname VARCHAR(100) NOT NULL, benutzer_id UUID NOT NULL, klassen_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_55F38D3C9F9AC274 ON persoenliche_daten (benutzer_id)');
        $this->addSql('CREATE INDEX IDX_55F38D3C2F869492 ON persoenliche_daten (klassen_id)');
        $this->addSql('CREATE TABLE stundenplan_alt (id UUID NOT NULL, summary VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, start TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, "end" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, location VARCHAR(255) DEFAULT NULL, label VARCHAR(50) DEFAULT NULL, kategorie kalender_kategorie DEFAULT NULL, original_event JSON DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, klasse VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE stundenplan_neu (id UUID NOT NULL, summary VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, start TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, "end" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, location VARCHAR(255) DEFAULT NULL, label VARCHAR(50) DEFAULT NULL, kategorie kalender_kategorie DEFAULT NULL, original_event JSON DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, klasse VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE persoenliche_daten ADD CONSTRAINT FK_55F38D3C9F9AC274 FOREIGN KEY (benutzer_id) REFERENCES benutzer (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE persoenliche_daten ADD CONSTRAINT FK_55F38D3C2F869492 FOREIGN KEY (klassen_id) REFERENCES klassen (klassen_id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE persoenliche_daten DROP CONSTRAINT FK_55F38D3C9F9AC274');
        $this->addSql('ALTER TABLE persoenliche_daten DROP CONSTRAINT FK_55F38D3C2F869492');
        $this->addSql('DROP TABLE benutzer');
        $this->addSql('DROP TABLE geaenderte_termine');
        $this->addSql('DROP TABLE klassen');
        $this->addSql('DROP TABLE persoenliche_daten');
        $this->addSql('DROP TABLE stundenplan_alt');
        $this->addSql('DROP TABLE stundenplan_neu');
    }
}
