<?php
/**
 * CalendarEvent
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App Calendar API
 *
 * Symfony-konforme REST API für Stundenplan und Terminverwaltung
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\OpenApi\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the CalendarEvent model.
 *
 * Termin des Stundenplans mit optionalen Metadaten
 *
 * @package App\OpenApi\Model
 * @author  OpenAPI Generator team
 */

class CalendarEvent 
{
        /**
     * @var string|null
     * @SerializedName("id")
     * @Type("string")
     */
    #[Assert\NotNull]
    #[Assert\Type("string")]
    protected ?string $id = null;

    /**
     * @var string|null
     * @SerializedName("summary")
     * @Type("string")
     */
    #[Assert\NotNull]
    #[Assert\Type("string")]
    #[Assert\Length(max: 255)]
    protected ?string $summary = null;

    /**
     * @var string|null
     * @SerializedName("description")
     * @Type("string")
     */
    #[Assert\Type("string")]
    protected ?string $description = null;

    /**
     * @var \DateTime|null
     * @SerializedName("start")
     * @Type("DateTime")
     */
    #[Assert\NotNull]
    #[Assert\Type("\DateTime")]
    protected ?\DateTime $start = null;

    /**
     * @var \DateTime|null
     * @SerializedName("end")
     * @Type("DateTime")
     */
    #[Assert\NotNull]
    #[Assert\Type("\DateTime")]
    protected ?\DateTime $end = null;

    /**
     * @var string|null
     * @SerializedName("location")
     * @Type("string")
     */
    #[Assert\Type("string")]
    protected ?string $location = null;

    /**
     * @var string|null
     * @SerializedName("lecturer")
     * @Type("string")
     */
    #[Assert\Type("string")]
    protected ?string $lecturer = null;

    /**
     * @var string|null
     * @SerializedName("label")
     * @Type("string")
     */
    #[Assert\Choice(['neu', 'gelöscht', 'geändert'])]
    #[Assert\Type("string")]
    protected ?string $label = null;

    /**
     * @var string|null
     * @SerializedName("category")
     * @Type("string")
     */
    #[Assert\Choice(['selbstlernzeit', 'ferien', 'klausur', 'bib-event', 'eigenes-event'])]
    #[Assert\Type("string")]
    protected ?string $category = null;

    /**
     * @var CalendarEventOriginalEvent|null
     * @SerializedName("originalEvent")
     * @Type("App\OpenApi\Model\CalendarEventOriginalEvent")
     */
    #[Assert\Type("App\OpenApi\Model\CalendarEventOriginalEvent")]
    protected ?CalendarEventOriginalEvent $originalEvent = null;

    /**
     * Zeitpunkt der letzten backendseitigen Aktualisierung eines geänderten Termins
     *
     * @var \DateTime|null
     * @SerializedName("updatedAt")
     * @Type("DateTime")
     */
    #[Assert\Type("\DateTime")]
    protected ?\DateTime $updatedAt = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        if (is_array($data)) {
            $this->id = array_key_exists('id', $data) ? $data['id'] : $this->id;
            $this->summary = array_key_exists('summary', $data) ? $data['summary'] : $this->summary;
            $this->description = array_key_exists('description', $data) ? $data['description'] : $this->description;
            $this->start = array_key_exists('start', $data) ? $data['start'] : $this->start;
            $this->end = array_key_exists('end', $data) ? $data['end'] : $this->end;
            $this->location = array_key_exists('location', $data) ? $data['location'] : $this->location;
            $this->lecturer = array_key_exists('lecturer', $data) ? $data['lecturer'] : $this->lecturer;
            $this->label = array_key_exists('label', $data) ? $data['label'] : $this->label;
            $this->category = array_key_exists('category', $data) ? $data['category'] : $this->category;
            $this->originalEvent = array_key_exists('originalEvent', $data) ? $data['originalEvent'] : $this->originalEvent;
            $this->updatedAt = array_key_exists('updatedAt', $data) ? $data['updatedAt'] : $this->updatedAt;
        }
    }

    /**
     * Gets id.
     *
     * @return string|null
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets id.
     *
     * @param string|null $id
     *
     * @return $this
     */
    public function setId(?string $id): self
    {
        $this->id = $id;

        return $this;
    }




    /**
     * Gets summary.
     *
     * @return string|null
     */
    public function getSummary(): ?string
    {
        return $this->summary;
    }

    /**
     * Sets summary.
     *
     * @param string|null $summary
     *
     * @return $this
     */
    public function setSummary(?string $summary): self
    {
        $this->summary = $summary;

        return $this;
    }




    /**
     * Gets description.
     *
     * @return string|null
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Sets description.
     *
     * @param string|null $description
     *
     * @return $this
     */
    public function setDescription(?string $description = null): self
    {
        $this->description = $description;

        return $this;
    }




    /**
     * Gets start.
     *
     * @return \DateTime|null
     */
    public function getStart(): ?\DateTime
    {
        return $this->start;
    }

    /**
     * Sets start.
     *
     * @param \DateTime|null $start
     *
     * @return $this
     */
    public function setStart(?\DateTime $start): self
    {
        $this->start = $start;

        return $this;
    }




    /**
     * Gets end.
     *
     * @return \DateTime|null
     */
    public function getEnd(): ?\DateTime
    {
        return $this->end;
    }

    /**
     * Sets end.
     *
     * @param \DateTime|null $end
     *
     * @return $this
     */
    public function setEnd(?\DateTime $end): self
    {
        $this->end = $end;

        return $this;
    }




    /**
     * Gets location.
     *
     * @return string|null
     */
    public function getLocation(): ?string
    {
        return $this->location;
    }

    /**
     * Sets location.
     *
     * @param string|null $location
     *
     * @return $this
     */
    public function setLocation(?string $location = null): self
    {
        $this->location = $location;

        return $this;
    }




    /**
     * Gets lecturer.
     *
     * @return string|null
     */
    public function getLecturer(): ?string
    {
        return $this->lecturer;
    }

    /**
     * Sets lecturer.
     *
     * @param string|null $lecturer
     *
     * @return $this
     */
    public function setLecturer(?string $lecturer = null): self
    {
        $this->lecturer = $lecturer;

        return $this;
    }




    /**
     * Gets label.
     *
     * @return string|null
     */
    public function getLabel(): ?string
    {
        return $this->label;
    }

    /**
     * Sets label.
     *
     * @param string|null $label
     *
     * @return $this
     */
    public function setLabel(?string $label = null): self
    {
        $this->label = $label;

        return $this;
    }




    /**
     * Gets category.
     *
     * @return string|null
     */
    public function getCategory(): ?string
    {
        return $this->category;
    }

    /**
     * Sets category.
     *
     * @param string|null $category
     *
     * @return $this
     */
    public function setCategory(?string $category = null): self
    {
        $this->category = $category;

        return $this;
    }




    /**
     * Gets originalEvent.
     *
     * @return CalendarEventOriginalEvent|null
     */
    public function getOriginalEvent(): ?CalendarEventOriginalEvent
    {
        return $this->originalEvent;
    }

    /**
     * Sets originalEvent.
     *
     * @param CalendarEventOriginalEvent|null $originalEvent
     *
     * @return $this
     */
    public function setOriginalEvent(?CalendarEventOriginalEvent $originalEvent = null): self
    {
        $this->originalEvent = $originalEvent;

        return $this;
    }




    /**
     * Gets updatedAt.
     *
     * @return \DateTime|null
     */
    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updatedAt;
    }

    /**
     * Sets updatedAt.
     *
     * @param \DateTime|null $updatedAt  Zeitpunkt der letzten backendseitigen Aktualisierung eines geänderten Termins
     *
     * @return $this
     */
    public function setUpdatedAt(?\DateTime $updatedAt = null): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }



}


