<?php
/**
 * CalendarEventOriginalEvent
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App Calendar API
 *
 * Symfony-konforme REST API für Stundenplan und Terminverwaltung
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\OpenApi\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the CalendarEventOriginalEvent model.
 *
 * @package App\OpenApi\Model
 * @author  OpenAPI Generator team
 */

class CalendarEventOriginalEvent 
{
        /**
     * @var string|null
     * @SerializedName("summary")
     * @Type("string")
     */
    #[Assert\NotNull]
    #[Assert\Type("string")]
    protected ?string $summary = null;

    /**
     * @var \DateTime|null
     * @SerializedName("start")
     * @Type("DateTime")
     */
    #[Assert\NotNull]
    #[Assert\Type("\DateTime")]
    protected ?\DateTime $start = null;

    /**
     * @var \DateTime|null
     * @SerializedName("end")
     * @Type("DateTime")
     */
    #[Assert\NotNull]
    #[Assert\Type("\DateTime")]
    protected ?\DateTime $end = null;

    /**
     * @var string|null
     * @SerializedName("location")
     * @Type("string")
     */
    #[Assert\Type("string")]
    protected ?string $location = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        if (is_array($data)) {
            $this->summary = array_key_exists('summary', $data) ? $data['summary'] : $this->summary;
            $this->start = array_key_exists('start', $data) ? $data['start'] : $this->start;
            $this->end = array_key_exists('end', $data) ? $data['end'] : $this->end;
            $this->location = array_key_exists('location', $data) ? $data['location'] : $this->location;
        }
    }

    /**
     * Gets summary.
     *
     * @return string|null
     */
    public function getSummary(): ?string
    {
        return $this->summary;
    }

    /**
     * Sets summary.
     *
     * @param string|null $summary
     *
     * @return $this
     */
    public function setSummary(?string $summary): self
    {
        $this->summary = $summary;

        return $this;
    }




    /**
     * Gets start.
     *
     * @return \DateTime|null
     */
    public function getStart(): ?\DateTime
    {
        return $this->start;
    }

    /**
     * Sets start.
     *
     * @param \DateTime|null $start
     *
     * @return $this
     */
    public function setStart(?\DateTime $start): self
    {
        $this->start = $start;

        return $this;
    }




    /**
     * Gets end.
     *
     * @return \DateTime|null
     */
    public function getEnd(): ?\DateTime
    {
        return $this->end;
    }

    /**
     * Sets end.
     *
     * @param \DateTime|null $end
     *
     * @return $this
     */
    public function setEnd(?\DateTime $end): self
    {
        $this->end = $end;

        return $this;
    }




    /**
     * Gets location.
     *
     * @return string|null
     */
    public function getLocation(): ?string
    {
        return $this->location;
    }

    /**
     * Sets location.
     *
     * @param string|null $location
     *
     * @return $this
     */
    public function setLocation(?string $location = null): self
    {
        $this->location = $location;

        return $this;
    }



}


