<?php
/**
 * GetCalendar200Response
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App Calendar API
 *
 * Symfony-konforme REST API für Stundenplan und Terminverwaltung
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\OpenApi\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the GetCalendar200Response model.
 *
 * @package App\OpenApi\Model
 * @author  OpenAPI Generator team
 */

class GetCalendar200Response
{
        /**
     * @var bool|null
     * @SerializedName("success")
     * @Type("bool")
     */
    #[Assert\NotNull]
    #[Assert\Type("bool")]
    protected ?bool $success = null;

    /**
     * @var CalendarEvent[]|null
     * @SerializedName("data")
     * @Type("array<App\OpenApi\Model\CalendarEvent>")
     */
    #[Assert\NotNull]
    #[Assert\Valid]
    #[Assert\All([
        new Assert\Type("App\OpenApi\Model\CalendarEvent"),
    ])]
    protected ?array $data = null;

    /**
     * Zeitpunkt der Erstellung der Antwort
     *
     * @var \DateTime|null
     * @SerializedName("timestamp")
     * @Type("DateTime")
     */
    #[Assert\NotNull]
    #[Assert\Type("\DateTime")]
    protected ?\DateTime $timestamp = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        if (is_array($data)) {
            $this->success = array_key_exists('success', $data) ? $data['success'] : $this->success;
            $this->data = array_key_exists('data', $data) ? $data['data'] : $this->data;
            $this->timestamp = array_key_exists('timestamp', $data) ? $data['timestamp'] : $this->timestamp;
        }
    }

    /**
     * Gets success.
     *
     * @return bool|null
     */
    public function isSuccess(): ?bool
    {
        return $this->success;
    }

    /**
     * Backwards-compatible getter used by tests/older code that expect getSuccess()
     *
     * @return bool|null
     */
    public function getSuccess(): ?bool
    {
        return $this->isSuccess();
    }
    /**
     * Sets success.
     *
     * @param bool|null $success
     *
     * @return $this
     */
    public function setSuccess(?bool $success): self
    {
        $this->success = $success;

        return $this;
    }




    /**
     * Gets data.
     *
     * @return CalendarEvent[]|null
     */
    public function getData(): ?array
    {
        return $this->data;
    }

    /**
     * Sets data.
     *
     * @param CalendarEvent[]|null $data
     *
     * @return $this
     */
    public function setData(?array $data): self
    {
        $this->data = $data;

        return $this;
    }




    /**
     * Gets timestamp.
     *
     * @return \DateTime|null
     */
    public function getTimestamp(): ?\DateTime
    {
        return $this->timestamp;
    }

    /**
     * Sets timestamp.
     *
     * @param \DateTime|null $timestamp  Zeitpunkt der Erstellung der Antwort
     *
     * @return $this
     */
    public function setTimestamp(?\DateTime $timestamp): self
    {
        $this->timestamp = $timestamp;

        return $this;
    }



}


