<?php
/**
 * GetCalendar200Response
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App Calendar API
 *
 * Symfony-konforme REST API für Stundenplan und Terminverwaltung
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\OpenApi\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the GetCalendar200Response model.
 *
 * @package App\OpenApi\Model
 * @author  OpenAPI Generator team
 */

class GetCalendar200Response 
{
        /**
     * Zeitpunkt der Erstellung der Antwort
     *
     * @var \DateTime|null
     * @SerializedName("timestamp")
     * @Type("DateTime")
     */
    #[Assert\NotNull]
    #[Assert\Type("\DateTime")]
    protected ?\DateTime $timestamp = null;

    /**
     * @var CalendarEvent[]|null
     * @SerializedName("events")
     * @Type("array<App\OpenApi\Model\CalendarEvent>")
     */
    #[Assert\NotNull]
    #[Assert\Valid]
    #[Assert\All([
        new Assert\Type("App\OpenApi\Model\CalendarEvent"),
    ])]
    protected ?array $events = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        if (is_array($data)) {
            $this->timestamp = array_key_exists('timestamp', $data) ? $data['timestamp'] : $this->timestamp;
            $this->events = array_key_exists('events', $data) ? $data['events'] : $this->events;
        }
    }

    /**
     * Gets timestamp.
     *
     * @return \DateTime|null
     */
    public function getTimestamp(): ?\DateTime
    {
        return $this->timestamp;
    }

    /**
     * Sets timestamp.
     *
     * @param \DateTime|null $timestamp  Zeitpunkt der Erstellung der Antwort
     *
     * @return $this
     */
    public function setTimestamp(?\DateTime $timestamp): self
    {
        $this->timestamp = $timestamp;

        return $this;
    }




    /**
     * Gets events.
     *
     * @return CalendarEvent[]|null
     */
    public function getEvents(): ?array
    {
        return $this->events;
    }

    /**
     * Sets events.
     *
     * @param CalendarEvent[]|null $events
     *
     * @return $this
     */
    public function setEvents(?array $events): self
    {
        $this->events = $events;

        return $this;
    }



}


