<?php
/**
 * Problem
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App Calendar API
 *
 * Symfony-konforme REST API für Stundenplan und Terminverwaltung
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\OpenApi\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Problem model.
 *
 * RFC-9457-kompatibles Problem-Detail-Objekt
 *
 * @package App\OpenApi\Model
 * @author  OpenAPI Generator team
 */

class Problem 
{
        /**
     * @var string|null
     * @SerializedName("type")
     * @Type("string")
     */
    #[Assert\Type("string")]
    protected ?string $type = 'about:blank';

    /**
     * @var string|null
     * @SerializedName("title")
     * @Type("string")
     */
    #[Assert\Type("string")]
    protected ?string $title = null;

    /**
     * @var int|null
     * @SerializedName("status")
     * @Type("int")
     */
    #[Assert\Type("int")]
    #[Assert\GreaterThanOrEqual(100)]
    #[Assert\LessThanOrEqual(599)]
    protected ?int $status = null;

    /**
     * @var string|null
     * @SerializedName("detail")
     * @Type("string")
     */
    #[Assert\Type("string")]
    protected ?string $detail = null;

    /**
     * @var string|null
     * @SerializedName("instance")
     * @Type("string")
     */
    #[Assert\Type("string")]
    protected ?string $instance = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        if (is_array($data)) {
            $this->type = array_key_exists('type', $data) ? $data['type'] : $this->type;
            $this->title = array_key_exists('title', $data) ? $data['title'] : $this->title;
            $this->status = array_key_exists('status', $data) ? $data['status'] : $this->status;
            $this->detail = array_key_exists('detail', $data) ? $data['detail'] : $this->detail;
            $this->instance = array_key_exists('instance', $data) ? $data['instance'] : $this->instance;
        }
    }

    /**
     * Gets type.
     *
     * @return string|null
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets type.
     *
     * @param string|null $type
     *
     * @return $this
     */
    public function setType(?string $type = null): self
    {
        $this->type = $type;

        return $this;
    }




    /**
     * Gets title.
     *
     * @return string|null
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * Sets title.
     *
     * @param string|null $title
     *
     * @return $this
     */
    public function setTitle(?string $title = null): self
    {
        $this->title = $title;

        return $this;
    }




    /**
     * Gets status.
     *
     * @return int|null
     */
    public function getStatus(): ?int
    {
        return $this->status;
    }

    /**
     * Sets status.
     *
     * @param int|null $status
     *
     * @return $this
     */
    public function setStatus(?int $status = null): self
    {
        $this->status = $status;

        return $this;
    }




    /**
     * Gets detail.
     *
     * @return string|null
     */
    public function getDetail(): ?string
    {
        return $this->detail;
    }

    /**
     * Sets detail.
     *
     * @param string|null $detail
     *
     * @return $this
     */
    public function setDetail(?string $detail = null): self
    {
        $this->detail = $detail;

        return $this;
    }




    /**
     * Gets instance.
     *
     * @return string|null
     */
    public function getInstance(): ?string
    {
        return $this->instance;
    }

    /**
     * Sets instance.
     *
     * @param string|null $instance
     *
     * @return $this
     */
    public function setInstance(?string $instance = null): self
    {
        $this->instance = $instance;

        return $this;
    }



}


