<?php
/**
 * UserProfile
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApi\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Bib-App Calendar API
 *
 * Symfony-konforme REST API für Stundenplan und Terminverwaltung
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\OpenApi\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the UserProfile model.
 *
 * Benutzerprofil-Daten
 *
 * @package App\OpenApi\Model
 * @author  OpenAPI Generator team
 */

class UserProfile 
{
        /**
     * Die eindeutige ID des Benutzers vom Identity Provider (sub claim).
     *
     * @var string|null
     * @SerializedName("identity_id")
     * @Type("string")
     */
    #[Assert\Type("string")]
    protected ?string $identityId = null;

    /**
     * @var string|null
     * @SerializedName("email")
     * @Type("string")
     */
    #[Assert\Type("string")]
    protected ?string $email = null;

    /**
     * @var bool|null
     * @SerializedName("is_admin")
     * @Type("bool")
     */
    #[Assert\Type("bool")]
    protected ?bool $isAdmin = null;

    /**
     * @var string[]|null
     * @SerializedName("roles")
     * @Type("array<string>")
     */
    #[Assert\All([
        new Assert\Type("string"),
    ])]
    protected ?array $roles = null;

    /**
     * @var Klasse|null
     * @SerializedName("klasse")
     * @Type("App\OpenApi\Model\Klasse")
     */
    #[Assert\Type("App\OpenApi\Model\Klasse")]
    protected ?Klasse $klasse = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        if (is_array($data)) {
            $this->identityId = array_key_exists('identityId', $data) ? $data['identityId'] : $this->identityId;
            $this->email = array_key_exists('email', $data) ? $data['email'] : $this->email;
            $this->isAdmin = array_key_exists('isAdmin', $data) ? $data['isAdmin'] : $this->isAdmin;
            $this->roles = array_key_exists('roles', $data) ? $data['roles'] : $this->roles;
            $this->klasse = array_key_exists('klasse', $data) ? $data['klasse'] : $this->klasse;
        }
    }

    /**
     * Gets identityId.
     *
     * @return string|null
     */
    public function getIdentityId(): ?string
    {
        return $this->identityId;
    }

    /**
     * Sets identityId.
     *
     * @param string|null $identityId  Die eindeutige ID des Benutzers vom Identity Provider (sub claim).
     *
     * @return $this
     */
    public function setIdentityId(?string $identityId = null): self
    {
        $this->identityId = $identityId;

        return $this;
    }




    /**
     * Gets email.
     *
     * @return string|null
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * Sets email.
     *
     * @param string|null $email
     *
     * @return $this
     */
    public function setEmail(?string $email = null): self
    {
        $this->email = $email;

        return $this;
    }




    /**
     * Gets isAdmin.
     *
     * @return bool|null
     */
    public function isIsAdmin(): ?bool
    {
        return $this->isAdmin;
    }

    /**
     * Sets isAdmin.
     *
     * @param bool|null $isAdmin
     *
     * @return $this
     */
    public function setIsAdmin(?bool $isAdmin = null): self
    {
        $this->isAdmin = $isAdmin;

        return $this;
    }




    /**
     * Gets roles.
     *
     * @return string[]|null
     */
    public function getRoles(): ?array
    {
        return $this->roles;
    }

    /**
     * Sets roles.
     *
     * @param string[]|null $roles
     *
     * @return $this
     */
    public function setRoles(?array $roles = null): self
    {
        $this->roles = $roles;

        return $this;
    }




    /**
     * Gets klasse.
     *
     * @return Klasse|null
     */
    public function getKlasse(): ?Klasse
    {
        return $this->klasse;
    }

    /**
     * Sets klasse.
     *
     * @param Klasse|null $klasse
     *
     * @return $this
     */
    public function setKlasse(?Klasse $klasse = null): self
    {
        $this->klasse = $klasse;

        return $this;
    }



}


